# 🏈 Fantasy Autopilot para Yahoo

Tu propio **Fantasy Plus + FantasyPros Auto-Pilot**, corriendo en Google Colab:

| Qué hace | Cómo decide |
|---|---|
| **Proyección propia** (celda 7e) | Sleeper en la puntuación de tu liga + un modelo entrenado con cada partido de la NFL (forma, snaps, targets, rival, línea de apuestas). En tus semanas 1–7 se equivocó menos que Yahoo (4.76 vs 4.98 pts por jugador) y ordenó mejor titular/banca (71% vs 69%). Si deja de ganarle a Yahoo, se usa Yahoo. |
| **Alineación óptima** cada semana | Suma la proyección propia con la asignación exacta a tus posiciones (incluye el FLEX). Solo cambia algo si sube tu valor esperado. |
| **Ganar la semana** (celdas 5d y 5e) | Para tu próximo partido: qué agentes libres suben más tu probabilidad de ganar (descansos, lesiones), a quién soltar y cuánto pujar; radar de descansos de las próximas semanas. |
| **Inactivos del día de partido** | Revisa cada 10–15 min antes de cada kickoff; si un titular sale *Out*, lo cambia por el mejor suplente que todavía no haya jugado. |
| **Jugadores dudosos (Q/D)** | Calcula la probabilidad de que jueguen (estado + prácticas). Si juega de noche y no tienes un suplente que juegue igual o más tarde, cuenta el riesgo de quedarte en cero (el caso Nacua). |
| **Waivers y pujas FAAB** | Mide cuántos puntos de *alineación* te da cada agente libre en lo que queda de temporada, a quién soltar, y cuánto pujar (con tu saldo y el de tus rivales). |
| **Rival y probabilidad de ganar** | Detecta errores en la alineación del rival (titulares en IR, banca mejor que titulares). |
| **Evaluador de trades** | Totales, titulares que se van, si lo que recibes mejora a tu mejor jugador de esa posición, y puntos de alineación antes/después. |
| **Avisos al celular** | App gratis **ntfy** (sin cuenta), y opcional Telegram o correo. |

**Modos** (celda 2):
* `sugerir` — solo te avisa; no toca Yahoo. **Empieza aquí.**
* `simulacro` — prueba los cambios en Yahoo sin guardarlos (para verificar que todo funciona).
* `automatico` — guarda los cambios de alineación en Yahoo. Las pujas solo se envían si además marcas `PUJAS_AUTOMATICAS`.

**Lo que debes saber antes:**
1. Desde el 22 de julio de 2026 Yahoo bloquea su API a programas no aprobados y **no da permiso de escritura a nadie**. Por eso este notebook usa **tu sesión del navegador (cookies)**: lee las mismas páginas que ves tú y guarda con los mismos formularios.
2. Automatizar tu cuenta puede ir contra los términos de uso de Yahoo. Es tu decisión; el programa hace pocas visitas y con pausas, como una persona.
3. Las páginas de Yahoo que se leen fueron verificadas por otros proyectos en agosto–septiembre de 2026, pero **el guardado de la alineación y el formulario de pujas no se pudieron probar contra Yahoo real** desde donde se construyó esto. Por eso: primero `simulacro`, mira las capturas (celda 9), y después `automatico`.
4. Colab solo corre **mientras esta pestaña esté abierta**. Para que funcione 24/7 con la computadora apagada, usa GitHub Actions (celda 10).

## Rutina semanal (orden de las celdas)

| Cuándo (hora del Este) | Celdas |
|---|---|
| **Martes** (antes de las pujas del miércoles ~3:30 am) | 1, 2, 3, **3b**, **7d** (aprende de la semana pasada), **7e** (examen de la proyección propia), **6** (waivers), **6c** (qué necesita cada equipo, predicción y bloqueos), **6d** (lesionados libres), **5b** (próximo rival), **5d** (ganar la semana: altas y pujas), **5e** (radar de descansos), **7c** (trades) |
| **Jueves** antes del partido de la noche | 3, 3b, 4, **4b** |
| **Domingo**, 90 min antes del primer partido de tus titulares (8:00 am si alguno juega a las 9:30 en Europa; si no, 11:30 am) | 3, 3b, 4, **4b**, y deja corriendo la 8 |
| **Una sola vez** | **6e** (temporadas pasadas de la liga; guarda todo en Drive) |

## Reglas fijas (aprendidas de errores reales)

1. **Activo no es lo mismo que titular.** Semana 6: Skattebo salió activo y tuvo 0 toques. Antes de cada partido corre la **4b** y lee la tarea del domingo: un titular con noticia de pérdida de rol cuenta a la mitad, y × 0.3 si además su uso ya bajó en el último partido.
2. Un cambio de alineación solo se hace si la suma de proyecciones sube; siempre con la resta escrita.
3. Un titular dudoso que juega de noche necesita un suplente que juegue a la misma hora o más tarde. Una hora antes de su partido, si no está en la lista de inactivos, el dudoso cuenta como activo (95%), no 75%. En modo `sugerir` nadie hace ese cambio por ti: la 3b cuenta ese respaldo a la mitad.
4. **Trades:** tus 5 mejores titulares nunca se ofrecen; máximo 1 titular por trade; el evaluador de Yahoo tiene que mostrarte +5 o más (solo banca) o +10 o más (con un titular) y al otro en verde. Nunca des a tu único mariscal suplente sin recibir otro mariscal.
5. **Proyecciones:** se usan las de Yahoo salvo que la 7d o la 7e demuestren una mejora clara (al menos 2% y más que la suerte entre semanas). La 7d guarda la proyección de *antes* del partido y lo comprueba con fotos propias (estado_log.csv).
6. **Banca útil:** no guardes dos pateadores ni dos defensas; la celda 6 marca esos lugares muertos y te dice qué corredor o receptor libre poner. También cambia tu corredor o receptor más flojo de la banca si hay uno libre claramente mejor (1.5 pts por semana o más) sin bajar tu alineación. El mariscal suplente se queda si cubre un descanso cercano (Purdy: semana 8).
7. **Suerte:** un equipo varía ±24 puntos por semana (medido en esta liga, semanas 1 a 6). Ejemplo real: semana 6 Yahoo te dio 119.78 e hiciste 79.36; ni la alineación perfecta (92.96) le ganaba a Mike (103.82). La 7d hace esta auditoría cada semana. Evita ceros (inactivos, descansos, pérdida de rol); no persigas los puntos de la semana pasada.
8. Pateador y defensa: se cambian cada semana por el mejor rival, gratis o $0–2.
9. **Bloqueos (6c):** solo contra un equipo arriba de ti o tu rival de esa semana, solo corredor/receptor/ala cerrada/mariscal, solo si el mejor libre le saca 2+ puntos al siguiente, y mejor si también te sirve a ti. Si es "solo bloqueo" y cuesta más de $3, no.
10. **Lesionados (6d):** si el IR está libre, guarda al mejor; en la banca, solo si vuelve antes de la semana 13 y le ganaría a tus titulares en playoffs.
11. **Predicciones de rivales:** la 6c mide qué tan bien predice con las semanas pasadas. No se promete un porcentaje: se usa el número medido.
12. **Pujadores fuertes (6c):** si un manager activo suele pagar más que tu puja (ej. Josh: típica $10, máxima $12), la 6c te avisa cuánto hace falta para ganarle. Sube solo si el jugador mejora tu alineación.

In [ ]:
#@title 1. Instalar (≈1–2 min) { display-mode: "form" }
RAMA = "claude/pensive-brown-ow1zrl"  #@param {type:"string"}
INSTALAR_NAVEGADOR = True  #@param {type:"boolean"}
#@markdown El navegador (Chromium) solo hace falta para pujas automáticas, capturas y como respaldo al guardar la alineación.

import sys
_ya_cargado = "fantasy_autopilot" in sys.modules
URL_PAQUETE = f"git+https://github.com/delioguzmang-maker/fanatasy.git@{RAMA}"
!pip -q install "{URL_PAQUETE}"
# Con la misma versión pip cree que "ya está" y deja el código viejo: se fuerza la última versión de la rama.
!pip -q install --force-reinstall --no-deps --no-cache-dir "{URL_PAQUETE}"
if INSTALAR_NAVEGADOR:
    !pip -q install playwright
    !python -m playwright install --with-deps chromium > /dev/null 2>&1
!python -c "import fantasy_autopilot as f; print('✅ Instalado:', f.build_info())"
if _ya_cargado:
    print("⚠ Esta sesión ya tenía cargada la versión anterior. Menú Entorno de ejecución → Reiniciar sesión "
          "y corre desde la celda 2 (la 1 no hace falta otra vez).")

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for fantasy-autopilot (pyproject.toml) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for fantasy-autopilot (pyproject.toml) ... done
✅ Instalado: 0.2.1 · commit f475e64

## 2. Tu liga

Abre tu equipo en la web de Yahoo. La dirección se ve así:

`https://football.fantasysports.yahoo.com/f1/`**`123456`**`/`**`7`**

El primer número es tu **LIGA_ID** y el segundo tu **EQUIPO_ID**.

* **NUNCA_SOLTAR**: nombres separados por coma (por ejemplo, jugadores en una oferta de trade pendiente: `Alec Pierce`).
* **PROBABILIDAD_MANUAL**: si una noticia dice algo que el estado Q/D no refleja, escribe `Puka Nacua=30%, Nico Collins=10%`.
* **TEMA_NTFY**: tu tema fijo de avisos. Instala la app **ntfy** (Android / iPhone), toca **+** y suscríbete a ese tema. Si lo borras, se crea uno nuevo y se guarda en Drive.

In [ ]:
#@title 2. Configuración { display-mode: "form" }
LIGA_ID = "43220"  #@param {type:"string"}
EQUIPO_ID = "13"  #@param {type:"string"}
MODO = "sugerir"  #@param ["sugerir", "simulacro", "automatico"]
PUJAS_AUTOMATICAS = False  #@param {type:"boolean"}
NUNCA_SOLTAR = ""  #@param {type:"string"}
PROBABILIDAD_MANUAL = ""  #@param {type:"string"}
PUJA_MAXIMA_PCT = 50  #@param {type:"slider", min:5, max:100, step:5}
TEMA_NTFY = "fantasy-4de4fa27e162"  #@param {type:"string"}
GUARDAR_EN_DRIVE = True  #@param {type:"boolean"}
#@markdown `GUARDAR_EN_DRIVE` guarda capturas, historial y tu tema de ntfy en tu Google Drive (carpeta fantasy_autopilot).

import os, secrets
from fantasy_autopilot import Config

carpeta = "/content/fantasy_autopilot"
if GUARDAR_EN_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")
    carpeta = "/content/drive/MyDrive/fantasy_autopilot"
os.makedirs(carpeta, exist_ok=True)

if not TEMA_NTFY:
    archivo_tema = os.path.join(carpeta, "tema_ntfy.txt")
    if os.path.exists(archivo_tema):
        TEMA_NTFY = open(archivo_tema).read().strip()
    else:
        TEMA_NTFY = "fantasy-" + secrets.token_hex(6)
        open(archivo_tema, "w").write(TEMA_NTFY)

probabilidades = {}
for parte in PROBABILIDAD_MANUAL.split(","):
    if "=" in parte:
        nombre, valor = parte.split("=", 1)
        v = float(valor.strip().rstrip("%"))
        probabilidades[nombre.strip()] = v / 100 if v > 1 else v

cfg = Config(
    league_id=LIGA_ID, team_id=EQUIPO_ID, mode=MODO, auto_claims=PUJAS_AUTOMATICAS,
    never_drop=[x.strip() for x in NUNCA_SOLTAR.split(",") if x.strip()],
    p_play_overrides=probabilidades, max_bid_pct=PUJA_MAXIMA_PCT / 100,
    ntfy_topic=TEMA_NTFY, state_dir=carpeta, quiet=True,
)
print(f"Modo: {cfg.mode} · pujas automáticas: {'sí' if cfg.auto_claims else 'no'}")
print(f"📱 En la app ntfy suscríbete al tema:  {TEMA_NTFY}")

Mounted at /content/drive
Modo: sugerir · pujas automáticas: no
📱 En la app ntfy suscríbete al tema:  fantasy-4de4fa27e162

## 3. Conectar con Yahoo (tus cookies)

Se hace **una vez** (y otra vez si Yahoo cierra tu sesión; el programa te avisa).

En una **computadora** con Chrome:
1. Entra a [football.fantasysports.yahoo.com](https://football.fantasysports.yahoo.com) con tu cuenta (marca *Mantener sesión iniciada*) y abre tu equipo.
2. Presiona **F12** → pestaña **Network** (Red) → recarga la página con **F5**.
3. Haz clic en la **primera fila** de la lista (lleva el número de tu liga).
4. En **Headers → Request Headers** busca **cookie:** y copia **todo** el valor (es largo).
5. Aquí en Colab: ícono de **llave 🔑** (Secrets) en la barra izquierda → **Add new secret** → Name: `YAHOO_COOKIES`, Value: pega → activa **Notebook access**.

⚠️ Ese valor es como tu contraseña de Yahoo: no lo pegues en chats ni lo subas a GitHub. Si cierras sesión en Yahoo deja de servir.

In [ ]:
#@title 3. Conectar y ver tu roster { display-mode: "form" }
import pandas as pd
from fantasy_autopilot import Autopilot
from fantasy_autopilot.report import when
from fantasy_autopilot.yahoo.cookies import describe, parse_cookies

try:
    from google.colab import userdata
    COOKIES = userdata.get("YAHOO_COOKIES")
except Exception:
    COOKIES = None
if not COOKIES:
    from getpass import getpass
    COOKIES = getpass("No encontré el secreto YAHOO_COOKIES. Pega aquí el valor de 'cookie' (no se muestra): ")

import fantasy_autopilot as _fa
print("Paquete:", _fa.build_info())
print("Cookies:", describe(parse_cookies(COOKIES)))
pilot = Autopilot(cfg, cookies=COOKIES)
semana = pilot.week()
roster = pilot.load_roster(semana)
pilot.enrich(roster.players, semana)
pilot.attach_actuals(roster)
print(f"Semana {semana} · posiciones: {', '.join(roster.slots)} · banca: {roster.bench_size} · IR: {roster.ir_size}")
display(pd.DataFrame([{
    "Puesto": p.slot, "Jugador": p.name, "Pos": p.position, "Equipo": p.team,
    "Proyección": round(p.proj, 2), "Puntos reales": "" if p.actual is None else round(p.actual, 2),
    "Estado": p.status or "", "Juega %": round(p.prob * 100),
    "Partido": when(p.kickoff, pilot.tz), "Bloqueado": "🔒" if p.locked else "",
} for p in roster.players]))
for aviso in pilot.warnings:
    print("⚠", aviso)

Paquete: 0.2.1 · commit f475e64
Cookies: 24 cookies (clave: T, Y, A1, A3, A1S)
Semana 8 · posiciones: QB, RB, RB, WR, WR, TE, W/R/T, K, DEF · banca: 9 · IR: 2

,Puesto,Jugador,Pos,Equipo,Proyección,Puntos reales,Estado,Juega %,Partido,Bloqueado
0,RB,Jaylen Warren,RB,PIT,12.52,,,100,dom 1:00 pm,
1,RB,Bucky Irving,RB,TB,14.29,,,100,dom 1:00 pm,
2,WR,Puka Nacua,WR,LAR,16.58,,,100,dom 4:05 pm,
3,WR,Denzel Boston,WR,CLE,8.01,,,100,dom 1:00 pm,
4,TE,Sam LaPorta,TE,DET,8.90,,,100,dom 1:00 pm,
5,W/R/T,Rachaad White,RB,WAS,9.39,,,100,dom 8:20 pm,
6,BN,Nico Collins,WR,HOU,0.00,,,0,hora ?,
7,BN,Brock Purdy,QB,SF,0.00,,,0,hora ?,
8,BN,Malik Washington,WR,MIA,6.83,,,100,dom 4:25 pm,
9,BN,Xavier Worthy,WR,KC,7.18,,,100,dom 4:25 pm,
10,BN,Cam Skattebo,RB,NYG,0.00,,Q,0,hora ?,
11,BN,Brenton Strange,TE,JAX,9.34,,,100,dom 1:00 pm,
12,BN,Geno Smith,QB,NYJ,19.37,,,100,dom 1:00 pm,
13,BN,Josh Downs,WR,IND,7.30,,,100,dom 1:00 pm,
14,IR,Michael Pittman Jr.,WR,PIT,0.00,,IR,0,dom 1:00 pm,
15,IR,Alec Pierce,WR,IND,0.00,,IR,0,dom 1:00 pm,
16,K,Spencer Shrader,K,IND,8.45,,,100,dom 1:00 pm,
17,BN,Lions,DEF,DET,6.65,,,100,dom 1:00 pm,

In [ ]:
#@title 3b. Parches de seguridad (córrela SIEMPRE justo después de la 3) { display-mode: "form" }
#@markdown **Desde el 22 de octubre estos parches vienen dentro del paquete** (también para GitHub Actions):
#@markdown memoria de páginas con caducidad (tu equipo y los guardados nunca se guardan), reintentos si Yahoo
#@markdown responde 999, lesiones de Sleeper frescas en día de partido, respaldo contado a la mitad en modo
#@markdown `sugerir`, libres lesionados descontados, notas de Yahoo que fallan y aviso de IR mal usado.
#@markdown Esta celda solo los aplica a mano si tienes instalada una versión vieja del paquete.
from fantasy_autopilot.yahoo import web as _web_chk
if hasattr(_web_chk.YahooWeb, "CACHE_TTL"):
    FALLOS_NOTAS = pilot.web.failed_notes  # la celda 6 lo revisa
    for _aviso in pilot.warnings:
        if _aviso.startswith("URGENTE"):
            print("⚠", _aviso)
    print("Parches incluidos en el paquete: no hace falta aplicar nada. Respaldo en día de partido:",
          pilot.opt_settings().hedge_reliability)
else:
    import time, random
    from datetime import datetime
    from zoneinfo import ZoneInfo
    from fantasy_autopilot.yahoo import web as _web
    from fantasy_autopilot import engine as _eng
    from fantasy_autopilot.sources import sleeper as _sl

    DIA_DE_PARTIDO = datetime.now(ZoneInfo("America/New_York")).weekday() in (0, 3, 6)  # lun, jue, dom

    # ---- 1. anti-bloqueo con caducidad ----
    TTL = {"/playernote": 600 if DIA_DE_PARTIDO else 900, "/players": 1800, "/teams": 600,
           "/settings": 86400, "/transactions": 900}
    _CACHE = {}
    if not hasattr(_web.YahooWeb, "_get_original"):
        _web.YahooWeb._get_original = _web.YahooWeb.get

    def _ttl(path):
        return next((v for p, v in TTL.items() if path.startswith(p)), 0)

    def _get_suave(self, path="", params=None):
        clave = (self.base_url, path, tuple(sorted((params or {}).items())))
        ttl = _ttl(path)
        if ttl and clave in _CACHE and time.time() - _CACHE[clave][0] < ttl:
            return _CACHE[clave][1]
        self.delay = max(self.delay, 3.0 if DIA_DE_PARTIDO else 4.0)
        esperas = (0, 30, 60, 120) if DIA_DE_PARTIDO else (0, 60, 180, 600)
        for espera in esperas:
            if espera:
                print(f"Yahoo frenó las visitas (HTTP 999). Espero {espera} s y reintento...")
                time.sleep(espera)
            try:
                pagina = _web.YahooWeb._get_original(self, path, params)
            except _web.YahooPageError as e:
                if "HTTP 999" not in str(e):
                    raise
                continue
            if ttl:
                _CACHE[clave] = (time.time(), pagina)
            time.sleep(random.uniform(0.3, 1.5))
            return pagina
        raise _web.YahooPageError("Yahoo sigue bloqueando (999). Para y vuelve a correr en 1 o 2 horas.")

    _web.YahooWeb.get = _get_suave

    # ---- 2. Sleeper fresco ----
    if not hasattr(_sl.Sleeper, "_players_original"):
        _sl.Sleeper._players_original = _sl.Sleeper.players

    def _players_frescos(self, max_age_hours=12.0):
        if self._players is not None and time.time() - getattr(self, "_t_carga", 0) > 1200:
            self._players = self._by_yahoo = self._by_name = None
        if self._players is None:
            self._t_carga = time.time()
        edad = min(max_age_hours, 0.33) if DIA_DE_PARTIDO else max_age_hours
        return _sl.Sleeper._players_original(self, max_age_hours=edad)

    _sl.Sleeper.players = _players_frescos

    # ---- 3. respaldo realista en modo sugerir ----
    if pilot.cfg.mode != "automatico":
        pilot.cfg.hedge_reliability = 0.5

    # ---- 4 y 5. agentes libres lesionados + notas que fallan ----
    FALLOS_NOTAS = []
    if not hasattr(_web.YahooWeb, "_playernote_original"):
        _web.YahooWeb._playernote_original = _web.YahooWeb.playernote

    def _playernote_contado(self, pid):
        try:
            return _web.YahooWeb._playernote_original(self, pid)
        except Exception as exc:  # noqa: BLE001
            FALLOS_NOTAS.append((pid, str(exc)[:80]))
            raise

    _web.YahooWeb.playernote = _playernote_contado

    if not hasattr(_eng.Autopilot, "_candidates_original"):
        _eng.Autopilot._candidates_original = _eng.Autopilot._candidates

    def _candidates_descontados(self, week, roster, slots):
        out = _eng.Autopilot._candidates_original(self, week, roster, slots)
        for c in out:
            _eng.apply_injury_outlook(c, week, status_is_for_this_game=True)
            c.proj = c.weekly.get(week, 0.0)
        return out

    if not getattr(_eng.Autopilot, "_CANDIDATES_INJURY", False):
        _eng.Autopilot._candidates = _candidates_descontados  # versión vieja del paquete
    # (la versión nueva del paquete ya descuenta a los libres lesionados: aplicarlo otra vez sería doble descuento)

    # ---- 6. IR mal usado ----
    mal_ir = [p.name for p in roster.players if p.slot == "IR" and p.status not in ("IR", "O", "PUP", "NFI", "SUSP", "D", "NA")]
    if mal_ir:
        print("⚠ URGENTE: en IR está alguien que ya no califica:", ", ".join(mal_ir),
              "→ Yahoo bloquea tus altas y bajas hasta que lo saques del IR.")
    print("Parches activos. Día de partido:", "sí" if DIA_DE_PARTIDO else "no",
          "· respaldo en día de partido vale", pilot.cfg.hedge_reliability)

Parches incluidos en el paquete: no hace falta aplicar nada. Respaldo en día de partido: 0.5

In [ ]:
#@title 4. Alineación de la semana { display-mode: "form" }
#@markdown En modo `sugerir` solo te dice qué cambiar; en `automatico` lo guarda en Yahoo y lo verifica.
r = pilot.run("lineup")
print(r.title, "\n")
print(r.text)

⚠ Alerta de rol: saca a Bucky Irving (+1.76)

Semana 8 · modo: solo sugerencias (no toca Yahoo)
Cambios (+26.46 pts proyectados):
  1. Sam LaPorta (TE, 8.90) → banca
  2. Lions (DEF, 6.65) → DEF
  3. Geno Smith (QB, 19.37) → QB
  4. Brenton Strange (TE, 9.34) → TE
Proyección Yahoo (suma simple): 78.14 → 104.60
Valor esperado con riesgo de inactivos: 78.14 → 104.60
Alineación recomendada:
  QB     Geno Smith                19.37
  RB     Bucky Irving              14.29
  RB     Jaylen Warren             12.52
  WR     Puka Nacua                16.58
  WR     Denzel Boston              8.01
  TE     Brenton Strange            9.34
  W/R/T  Rachaad White              9.39
  K      Spencer Shrader            8.45
  DEF    Lions                      6.65
Jugadores dudosos:
  Cam Skattebo (Q, juega 0%, hora ?) — fuera
Hazlo en la app de Yahoo (modo sugerir: no se tocó nada).
https://football.fantasysports.yahoo.com/f1/43220/13
ALERTA DE ROL (titular activo que puede no jugar mucho):
  ⚠ Bucky Irving (RB) puede haber perdido el puesto (noticia reciente): «He also committed a fumble that stayed with Tampa Bay.». Escenario si de verdad perdió el rol (no es una medición): 14.29 × 0.5 = 7.14.
  ⚠ Sam LaPorta (TE): en su último partido tuvo 2 toques (acarreos + pases a él) contra 9.0 de costumbre. Sin noticia de rol: Yahoo ya suele bajar su proyección (8.90); revisa antes de dejarlo de titular.
  → Contando la alerta, la mejor alineación cambia: Bucky Irving RB→BN, Rachaad White W/R/T→RB, Sam LaPorta BN→TE, Brenton Strange TE→W/R/T. 99.21 - 97.45 = +1.76 (con el castigo de rol).
  Las palabras clave pueden dar falsas alarmas: lee la noticia y cambia tú en Yahoo.
  ✓ Xavier Worthy (banca): señal buena «Worthy paced the Chiefs with seven catches on as many targets for 73 yards in a Week 6 win against the Chargers, and the third-year wideout once again will lead»
PLAZO: haz estos cambios en Yahoo antes de las dom 1:00 pm (empieza el primer partido de los jugadores que se mueven). Esta alerta se repite hasta que Yahoo muestre la alineación nueva.
PRÓXIMO CONTROL: dom 11:35 am, cuando salen los inactivos del partido de Jaylen Warren (dom 1:00 pm). Revisa ahí también la alerta de rol.

In [ ]:
#@title 4b. Alerta de rol: ¿alguno de tus titulares perdió el puesto? { display-mode: "form" }
#@markdown **Por qué existe:** en la semana 6 Cam Skattebo salió *activo* y no tocó el balón (sus pérdidas de balón
#@markdown lo sacaron de la rotación). Revisar solo la lista de inactivos no lo detecta.
#@markdown Lee la nota de Yahoo de cada titular, se queda **solo con noticias recientes** (por la fecha que trae),
#@markdown busca palabras de pérdida de rol y recalcula tu mejor alineación contando a ese titular con castigo.
#@markdown Las palabras de lesión (dudoso, fuera) no cuentan aquí: el estado de lesión ya las descuenta.
#@markdown **Uso real (Sleeper):** si además en su último partido tuvo menos del 40% de sus toques de costumbre,
#@markdown la pérdida de rol se da por confirmada y cuenta × 0.3. Si solo bajó el uso, sin noticia, solo avisa
#@markdown (Yahoo ya suele bajar su proyección y no se descuenta dos veces).
#@markdown La celda 8 (piloto del domingo) hace esta misma revisión sola y te manda alerta urgente.
#@markdown **Córrela 90 minutos antes del primer partido de tus titulares** (9:30 am en Europa: a las 8:00 am; si no, después de las 11:30 am) y antes del jueves.
CASTIGO_ROL = 0.5  #@param {type:"number"}
HORAS_NOTICIA = 120  #@param {type:"number"}
from fantasy_autopilot.optimizer import optimize_lineup

pilot.cfg.role_penalty = CASTIGO_ROL
pilot.cfg.role_news_hours = HORAS_NOTICIA
ros_4b = pilot.load_roster(semana)
pilot.enrich(ros_4b.players, semana)
alertas_4b, buenas_4b = pilot.role_alerts(ros_4b)
if not alertas_4b:
    print(f"Ninguna noticia de pérdida de rol en tus titulares (últimas {HORAS_NOTICIA:g} horas).")
else:
    plan_4b = optimize_lineup(ros_4b.players, ros_4b.slots, pilot.opt_settings())
    linea, ganancia, sacar = pilot._role_replan(ros_4b, plan_4b, alertas_4b, pilot.opt_settings())
    display(pd.DataFrame([{
        "Titular": a.name, "Puesto": a.slot, "Proyección": round(a.proj, 2),
        "Contando la alerta": round(a.effective, 2), "Fecha": "sin fecha" if a.undated else "reciente",
        "Noticia": " | ".join(a.sentences)[:200],
    } for a in alertas_4b]))
    print(("CAMBIA. " if ganancia > 0.01 else "") + linea)
for b in buenas_4b:
    print("Señal buena:", b)
for aviso in pilot.warnings:
    print("⚠", aviso)
print("Las palabras clave pueden dar falsas alarmas: lee la noticia antes de cambiar.")

,Titular,Puesto,Proyección,Contando la alerta,Fecha,Noticia
0,Bucky Irving,RB,14.29,7.14,reciente,He also committed a fumble that stayed with Ta...
1,Sam LaPorta,TE,8.90,8.90,reciente,

CAMBIA. Contando la alerta, la mejor alineación cambia: Bucky Irving RB→BN, Rachaad White W/R/T→RB, Sam LaPorta BN→TE, Brenton Strange TE→W/R/T. 99.21 - 97.45 = +1.76 (con el castigo de rol).
Señal buena: Xavier Worthy (banca): señal buena «Worthy paced the Chiefs with seven catches on as many targets for 73 yards in a Week 6 win against the Chargers, and the third-year wideout once again will lead»
Las palabras clave pueden dar falsas alarmas: lee la noticia antes de cambiar.

In [ ]:
#@title 5. Tu rival y probabilidad de ganar { display-mode: "form" }
r = pilot.run("matchup")
print(r.title, "\n")
print(r.text)

Semana 8: 27% de ganar

Semana 8: Fourth Quarter Delio vs Mountain Drew
Final esperado: 78.14 vs 93.10
Si el rival corrige lo que todavía puede mover: 96.09 (+2.99)
Probabilidad de ganar (modelo normal): 27% · 24% si el rival corrige
Errores que el rival todavía puede corregir:
  • Braelon Allen (9.03) está en la banca y Blake Corum (7.07) juega
  • Omarion Hampton (8.66) está en la banca y Blake Corum (7.07) juega
  • Ladd McConkey (7.74) está en la banca y Blake Corum (7.07) juega
  • Broncos (5.95) está en la banca y Chiefs (5.87) juega
La probabilidad es una estimación con volatilidades típicas por posición, no un dato de Yahoo.

In [ ]:
#@title 5b. Próximo rival y estrategia { display-mode: "form" }
#@markdown Después de que termina tu semana (lunes/martes) prepara la siguiente: resultados anteriores de los dos,
#@markdown tu mejor alineación contra la de él posición por posición, probabilidad de ganar, semanas de descanso
#@markdown y agentes libres que suben tu alineación **de esa semana**. Tarda 1–2 minutos.
BUSCAR_AGENTES_LIBRES = True  #@param {type:"boolean"}
r = pilot.run("preview", with_waivers=BUSCAR_AGENTES_LIBRES)
print(r.title, "\n")
print(r.text)

Semana 8 vs Mountain Drew: 62% de ganar

Semana 8: Fourth Quarter Delio vs Mountain Drew
Resultados anteriores (tú / rival):
  S1: 106.30 (P)  /  97.40 (P)
  S2: 63.48 (P)  /  83.36 (P)
  S3: 116.38 (G)  /  69.94 (P)
  S4: 151.32 (G)  /  78.28 (P)
  S5: 175.46 (G)  /  81.34 (P)
  S6: 79.36 (P)  /  91.70 (G)
  S7: 88.92 (G)  /  127.92 (G)
Promedio: tú 111.60 · rival 89.99 (+21.61)
Proyección de la semana 8 (mejor alineación de cada uno): tú 104.60 · rival 96.09 (+8.51)
Probabilidad de ganar (modelo normal): 62%
Posición por posición (puntos esperados, ya descontado el riesgo de lesión):
  QB     Geno Smith 19.4              vs Trevor Lawrence 24.2         -4.8
  RB     Bucky Irving 14.3            vs Jordan Mason 9.9             +4.3
  RB     Jaylen Warren 12.5           vs Braelon Allen 9.0            +3.5
  WR     Puka Nacua 16.6              vs Carnell Tate 10.0            +6.6
  WR     Denzel Boston 8.0            vs Amon-Ra St. Brown 9.7        -1.7
  TE     Brenton Strange 9.3          vs Colston Loveland 8.2         +1.2
  W/R/T  Rachaad White 9.4            vs Omarion Hampton 8.7          +0.7
  K      Spencer Shrader 8.4          vs Cam Little 10.5              -2.0
  DEF    Lions 6.7                    vs Broncos 6.0                  +0.7
Tus jugadores en semana de descanso: Nico Collins, Brock Purdy, Cam Skattebo
Sus jugadores en semana de descanso: Kaelon Black
Estrategia:
  • El rival promedia 90.0 pts en 7 semanas; tu mejor alineación proyecta 104.6 (+14.6 contra su promedio).
  • Llegas 8.5 pts arriba. Entre dos jugadores parecidos elige el más seguro (más balones garantizados): no te hace falta arriesgar.
  • Donde él es más fuerte: QB (-4.8), K (-2.0), WR (-1.7). Ahí es donde un agente libre te acerca más.

In [ ]:
#@title 5c. Rosters de toda la liga { display-mode: "form" }
#@markdown Lee el roster de los 12 equipos (útil para trades y para ver qué defensas están libres).
print(f"Rosters de todos los equipos para la semana {semana}...\n")
for equipo in pilot.web.teams():
    print(f"=== {equipo.name} ({equipo.manager}) ===")
    try:
        ros = pilot.load_roster(semana, team_id=str(equipo.team_id))
        pilot.enrich(ros.players, semana)
        display(pd.DataFrame([{
            "Puesto": p.slot, "Jugador": p.name, "Pos": p.position, "Equipo NFL": p.team,
            "Estado": p.status or "", "Proyección": round(p.proj, 2) if p.proj is not None else 0.0,
        } for p in ros.players]))
    except Exception as e:  # noqa: BLE001
        print(f"No se pudo cargar el roster de este equipo: {e}")
    print()

Rosters de todos los equipos para la semana 8...

=== 0-17 (Gregg) ===

   Puesto            Jugador  Pos Equipo NFL Estado  Proyección
0      QB        C.J. Stroud   QB        HOU               0.00
1      RB     Kyren Williams   RB        LAR              17.97
2      RB       Alvin Kamara   RB         NO               0.00
3      WR  Tetairoa McMillan   WR        CAR              11.28
4      WR   Courtland Sutton   WR        DEN               5.93
5      TE       Travis Kelce   TE         KC               8.88
6   W/R/T     Saquon Barkley   RB        PHI      Q        9.36
7      BN        Evan Engram   TE        DEN               3.93
8      BN     MarShawn Lloyd   RB         GB               6.41
9      BN      Khalil Shakir   WR        BUF               7.70
10     BN         Josh Allen   QB        BUF              25.01
11     BN         Mike Evans   WR         SF      O        0.00
12     BN   Deebo Samuel Sr.   WR         SF      O        0.00
13     BN   Chris Godwin Jr.   WR         TB               8.30
14      K    Andy Borregales    K         NE               9.05
15    DEF               Jets  DEF        NYJ               5.63

=== At least I'm not Dallas (JOSHUA) ===

   Puesto           Jugador  Pos Equipo NFL Estado  Proyección
0      QB   Jacoby Brissett   QB        ARI              20.69
1      RB    Bijan Robinson   RB        ATL              17.45
2      RB   Ollie Gordon II   RB        MIA              10.62
3      WR  Christian Watson   WR         GB              12.53
4      WR    Germie Bernard   WR        PIT               7.90
5      TE      Brock Bowers   TE         LV              12.66
6   W/R/T    Bhayshul Tuten   RB        JAX              13.87
7      BN        Jared Goff   QB        DET              18.98
8      BN      Malik Nabers   WR        NYG               0.00
9      BN       Chris Olave   WR         NO               0.00
10     BN    T.J. Hockenson   TE        MIN               9.02
11     BN        Cade Otton   TE         TB               6.78
12     BN     Caleb Douglas   WR        MIA               4.87
13      K     Chris Boswell    K        PIT               9.16
14    DEF           Bengals  DEF        CIN               7.71
15     BN            Texans  DEF        HOU               0.00

=== Better Luck NextYear (Ron) ===

   Puesto              Jugador  Pos Equipo NFL Estado  Proyección
0      QB         Tyler Shough   QB         NO               0.00
1      RB  Mike Washington Jr.   RB         LV               4.99
2      RB        Jonah Coleman   RB        DEN               8.36
3      WR          CeeDee Lamb   WR        DAL              17.64
4      WR     Justin Jefferson   WR        MIN              13.35
5      TE    Harold Fannin Jr.   TE        CLE               7.90
6   W/R/T        Juwan Johnson   TE         NO               0.00
7      BN       Jordan Addison   WR        MIN               7.64
8      BN          Tee Higgins   WR        CIN              12.87
9      BN          Breece Hall   RB        NYJ      Q       10.15
10     BN  Marvin Harrison Jr.   WR        HOU               0.00
11     BN       Jayden Daniels   QB        WAS              18.83
12     IR     David Montgomery   RB        HOU      O        0.00
13      K        Will Reichard    K        MIN               9.61
14    DEF             Steelers  DEF        PIT               7.90

=== End Zone Hunters (Douglas) ===

   Puesto             Jugador  Pos Equipo NFL Estado  Proyección
0      QB    Matthew Stafford   QB        LAR              19.68
1      RB       Derrick Henry   RB        BAL              14.76
2      RB         Woody Marks   RB        HOU      Q        0.00
3      WR  Jaxon Smith-Njigba   WR        SEA              18.84
4      WR       Jaylen Waddle   WR        DEN      Q        8.23
5      TE        Tucker Kraft   TE         GB               9.10
6   W/R/T     Aaron Jones Sr.   RB        MIN      Q        8.37
7      BN         Rico Dowdle   RB        PIT               7.81
8      BN        Emeka Egbuka   WR         TB      Q        9.66
9      BN          Drake Maye   QB         NE              23.36
10     BN        Hunter Henry   TE         NE               8.68
11     BN        Stefon Diggs   WR        WAS               8.74
12      K      Brandon Aubrey    K        DAL              10.95
13     BN          Tyler Bass    K        BUF               9.39
14    DEF            Seahawks  DEF        SEA               6.45
15     BN             Jaguars  DEF        JAX               7.20

=== Fahim n Furious (Fahim) ===

   Puesto              Jugador  Pos Equipo NFL Estado  Proyección
0      QB         Dak Prescott   QB        DAL              26.65
1      RB  Christian McCaffrey   RB         SF      Q        0.00
2      RB          Chase Brown   RB        CIN              16.81
3      WR     Jameson Williams   WR        DET               8.69
4      WR    Parker Washington   WR        JAX              12.89
5      TE         Trey McBride   TE        ARI              14.84
6   W/R/T       Jeremiyah Love   RB        ARI      Q        8.46
7      BN     Brian Thomas Jr.   WR        JAX               3.43
8      BN   De'Zhaun Stribling   WR         SF     IR        0.00
9      BN        Kyle Monangai   RB        CHI      Q        4.69
10     BN         Malik Willis   QB        MIA              13.62
11     BN        Jake Ferguson   TE        DAL               8.87
12     BN          Tank Bigsby   RB        PHI     IR        0.00
13     BN      Adonai Mitchell   WR        NYJ               4.39
14      K         Eddy Pineiro    K         SF               0.00
15    DEF             Patriots  DEF         NE               7.64

=== Fourth Quarter Delio (Delio) ===

   Puesto              Jugador  Pos Equipo NFL Estado  Proyección
0      RB        Jaylen Warren   RB        PIT              12.52
1      RB         Bucky Irving   RB         TB              14.29
2      WR           Puka Nacua   WR        LAR              16.58
3      WR        Denzel Boston   WR        CLE               8.01
4      TE          Sam LaPorta   TE        DET               8.90
5   W/R/T        Rachaad White   RB        WAS               9.39
6      BN         Nico Collins   WR        HOU               0.00
7      BN          Brock Purdy   QB         SF               0.00
8      BN     Malik Washington   WR        MIA               6.83
9      BN        Xavier Worthy   WR         KC               7.18
10     BN         Cam Skattebo   RB        NYG      Q        0.00
11     BN      Brenton Strange   TE        JAX               9.34
12     BN           Geno Smith   QB        NYJ              19.37
13     BN           Josh Downs   WR        IND               7.30
14     IR  Michael Pittman Jr.   WR        PIT     IR        0.00
15     IR          Alec Pierce   WR        IND     IR        0.00
16      K      Spencer Shrader    K        IND               8.45
17     BN                Lions  DEF        DET               6.65

=== Guap Goblin (Brian) ===

   Puesto             Jugador  Pos Equipo NFL Estado  Proyección
0      QB   Michael Penix Jr.   QB        ATL              16.73
1      RB       D'Andre Swift   RB        CHI              10.90
2      RB  Kenneth Walker III   RB         KC              16.88
3      WR   Luther Burden III   WR        CHI               9.12
4      WR         Jalen Coker   WR        CAR              11.49
5      TE      Dallas Goedert   TE        PHI               8.23
6   W/R/T          DK Metcalf   WR        PIT               9.34
7      BN            DJ Moore   WR        BUF      Q       11.51
8      BN        Mark Andrews   TE        BAL               7.64
9      BN         Romeo Doubs   WR         NE     IR        0.00
10     BN  Brian Robinson Jr.   RB        ATL      Q        3.52
11     BN         Jerry Jeudy   WR        CLE               2.87
12     BN         Cooper Kupp   WR        SEA               6.36
13      K        Cairo Santos    K        CHI               8.33
14    DEF              Ravens  DEF        BAL               3.93

=== Mountain Drew (Drew Commissioner) ===

   Puesto            Jugador  Pos Equipo NFL Estado  Proyección
0      QB    Trevor Lawrence   QB        JAX              24.20
1      RB   Quinshon Judkins   RB        CLE               7.71
2      RB       Jordan Mason   RB        MIN               9.94
3      WR       Carnell Tate   WR        TEN               9.96
4      WR  Amon-Ra St. Brown   WR        DET      Q       12.93
5      TE   Colston Loveland   TE        CHI               8.18
6   W/R/T        Blake Corum   RB        LAR               7.07
7      BN      Ladd McConkey   WR        LAC      Q        7.74
8      BN    Omarion Hampton   RB        LAC               8.66
9      BN      Braelon Allen   RB        NYJ               9.03
10     BN     Caleb Williams   QB        CHI              16.68
11     BN       Kaelon Black   RB         SF               0.00
12     IR        Rashee Rice   WR         KC      Q        9.06
13     IR    Zach Charbonnet   RB        SEA      Q        8.27
14      K         Cam Little    K        JAX              10.47
15     BN         Jake Bates    K        DET               9.42
16    DEF             Chiefs  DEF         KC               5.87
17     BN            Broncos  DEF        DEN               5.95

=== Mountain Top (Tito) ===

   Puesto              Jugador  Pos Equipo NFL Estado  Proyección
0      QB          Jordan Love   QB         GB              20.06
1      RB      Jonathan Taylor   RB        IND              13.68
2      RB  Rhamondre Stevenson   RB         NE               9.45
3      WR       Michael Wilson   WR        ARI              12.37
4      WR          Rome Odunze   WR        CHI               8.12
5      TE       Dalton Kincaid   TE        BUF               8.89
6   W/R/T          Josh Jacobs   RB         GB              14.57
7      BN       Dalton Schultz   TE        HOU               0.00
8      BN        DeVonta Smith   WR        PHI      Q        8.71
9      BN        Kalif Raymond   WR        CHI               5.20
10     BN       Deshaun Watson   QB        CLE              13.23
11     BN        Lamar Jackson   QB        BAL      Q       21.80
12     BN        Devaughn Vele   WR         NO               0.00
13      K       Evan McPherson    K        CIN              10.34
14     BN          Blake Grupe    K        LAR     IR        0.00
15    DEF              Vikings  DEF        MIN               5.51

=== Riddle Renegades (Keith) ===

   Puesto                 Jugador  Pos Equipo NFL Estado  Proyección
0      QB              Joe Burrow   QB        CIN              24.72
1      RB        Javonte Williams   RB        DAL              18.42
2      RB            Tony Pollard   RB        TEN              10.20
3      WR              Tre Tucker   WR         LV               8.47
4      WR           Ja'Marr Chase   WR        CIN              15.93
5      TE          Kyle Pitts Sr.   TE        ATL               7.27
6   W/R/T              A.J. Brown   WR         NE              12.22
7      BN           Isaiah Likely   TE        NYG               0.00
8      BN  Jacory Croskey-Merritt   RB        WAS     IR        0.00
9      BN       KC Concepcion Jr.   WR        CLE               7.32
10     BN         Patrick Mahomes   QB         KC              16.78
11     BN       Wan'Dale Robinson   WR        TEN               7.98
12     BN            Keon Coleman   WR        BUF               6.65
13     BN          Tyler Allgeier   RB        ARI               6.52
14      K        Chase McLaughlin    K         TB               9.58
15    DEF                   Bears  DEF        CHI               5.69

=== Silly Old Sawyer (mike) ===

   Puesto             Jugador  Pos Equipo NFL Estado  Proyección
0      QB       Aaron Rodgers   QB        PIT              17.87
1      RB       Chuba Hubbard   RB        CAR              13.90
2      RB        Jahmyr Gibbs   RB        DET              20.10
3      WR      Garrett Wilson   WR        NYJ              12.25
4      WR        Drake London   WR        ATL              12.88
5      TE        Tyler Warren   TE        IND      Q        7.91
6   W/R/T       Ashton Jeanty   RB         LV              13.56
7      BN      Matthew Golden   WR         GB      Q       11.02
8      BN  TreVeyon Henderson   RB         NE               6.77
9      BN        J.K. Dobbins   RB        DEN               5.05
10     BN        Kyler Murray   QB        MIN              18.71
11     BN        Chig Okonkwo   TE        WAS               6.05
12     BN        Jordyn Tyson   WR         NO     IR        0.00
13     BN           Ray Davis   RB        BUF               0.95
14      K    Ka'imi Fairbairn    K        HOU               0.00
15    DEF            Panthers  DEF        CAR               4.70

=== T-Law & Fornication (Preston) ===

   Puesto             Jugador  Pos Equipo NFL Estado  Proyección
0      QB         Bryce Young   QB        CAR              17.56
1      RB           RJ Harvey   RB        DEN               6.08
2      RB      James Cook III   RB        BUF              15.90
3      WR         Zay Flowers   WR        BAL              14.10
4      WR      George Pickens   WR        DAL              12.49
5      TE      Pat Freiermuth   TE        PIT               7.31
6   W/R/T     Omar Cooper Jr.   WR        NYJ               7.36
7      BN       George Kittle   TE         SF               0.00
8      BN          Bam Knight   RB        ARI               6.28
9      BN       Davante Adams   WR        LAR     IR        0.00
10     BN              Bo Nix   QB        DEN              14.84
11     BN       Jakobi Meyers   WR        JAX               8.57
12     BN    Antonio Williams   WR        WAS               5.78
13     IR      Jadarian Price   RB        SEA     IR        0.00
14     IR  Travis Etienne Jr.   RB         NO     IR        0.00
15      K         Jason Myers    K        SEA               9.81
16    DEF                Rams  DEF        LAR               6.99
17     BN             Cowboys  DEF        DAL               4.95

In [ ]:
#@title 5d. Ganar la semana: altas, bajas y pujas para tu próximo partido { display-mode: "form" }
#@markdown Para tu próximo partido (la semana que viene, o la actual si todavía no empieza): con tus descansos y
#@markdown lesiones, qué agentes libres suben más tu **probabilidad de ganar** contra tu rival, a quién soltar sin
#@markdown perder valor para el resto de la temporada y cuánto pujar. Los agentes libres (FA) se agregan YA, antes que
#@markdown otro; los de waivers se pujan antes del proceso (miércoles de madrugada). Usa la proyección propia (7e).
MAXIMO_CAMBIOS = 2  #@param {type:"slider", min:1, max:3, step:1}
r_ganar = pilot.run("win_week", max_adds=MAXIMO_CAMBIOS)
print(r_ganar.title, "\n")
print(r_ganar.text)

Semana 8: 62% → 63% con Harrison Butker

Semana 8 vs Mountain Drew (proyección propia):
  Hoy: tú 104.6 ± 20 · rival 96.1 ± 18 → 62% de ganar
  Tus jugadores en descanso: Nico Collins (WR), Brock Purdy (QB), Cam Skattebo (RB)
  Sus jugadores en descanso: Kaelon Black (RB)
MEJOR PLAN: 62% → 63% de ganar (alineación 104.9, +0.3 esta semana; resto de temporada +0.8 pts)
  + Harrison Butker (K, KC) 8.8 pts — suelta a Spencer Shrader · agente libre: agrégalo YA, antes que otro
  Alineación con este plan:
    QB     Geno Smith 19.4 (Yahoo 19.7)
    RB     Bucky Irving 14.3 (Yahoo 14.7)
    RB     Jaylen Warren 12.5 (Yahoo 13.6)
    WR     Puka Nacua 16.6 (Yahoo 19.2)
    WR     Denzel Boston 8.0 (Yahoo 9.0)
    TE     Brenton Strange 9.3 (Yahoo 8.4)
    W/R/T  Rachaad White 9.4 (Yahoo 11.0)
    K      Harrison Butker 8.8
    DEF    Lions 6.7
  Cómo salió la puja: agente libre: se agrega de inmediato, sin puja
Los puntos del resto de la temporada se cobran: perder 1 punto de alineación en semanas futuras cuesta lo mismo que 1.5 puntos de % de ganar esta semana.

In [ ]:
#@title 5e. Radar de descansos: tus próximas semanas { display-mode: "form" }
#@markdown Tu mejor alineación de cada una de las próximas semanas con descansos (calendario de nflverse) y lesiones:
#@markdown qué puestos quedan vacíos o débiles y qué agentes libres los cubren. Prepárate 1–2 semanas antes:
#@markdown la misma semana del descanso todos buscan lo mismo.
SEMANAS_RADAR = 5  #@param {type:"slider", min:2, max:8, step:1}
r_radar = pilot.run("bye_radar", weeks_ahead=SEMANAS_RADAR)
print(r_radar.title, "\n")
print(r_radar.text)

Byes: la peor semana es la 8 (-12 pts)

Radar de descansos y huecos (tu mejor alineación de cada semana, proyección de Yahoo por semana):
⚠ Semana 8: 104.6 pts (-12.3 contra tu semana normal)
    No juegan: Nico Collins (WR, HOU), Brock Purdy (QB, SF), Cam Skattebo (RB, NYG)
  Semana 9: 118.6 pts (+1.7 contra tu semana normal)
    No juegan: Jaylen Warren (RB, PIT)
  Semana 10: 118.6 pts (+1.7 contra tu semana normal)
    No juegan: Bucky Irving (RB, TB)
⚠ Semana 11: 106.3 pts (-10.6 contra tu semana normal)
    No juegan: Puka Nacua (WR, LAR), Denzel Boston (WR, CLE)
  Semana 12: 118.9 pts (+2.0 contra tu semana normal)
Consejo: el que cubre una semana mala se consigue barato 1–2 semanas antes; la misma semana lo buscan todos.

In [ ]:
#@title 6. Waivers y pujas FAAB { display-mode: "form" }
#@markdown Lee ~50–80 páginas de Yahoo con pausas: tarda 1–2 minutos. Córrelo el martes antes de que se procesen las pujas.
r = pilot.run("waivers")
r_waivers = r  # la celda 6c revisa quién te puede quitar estas pujas
print(r.title, "\n")
print(r.text)
cands = r.data.get("candidates", []) if r.data else []
if cands:
    display(pd.DataFrame([{
        "Jugador": c.name, "Pos": c.position, "Equipo": c.team, "Disponible": c.owner,
        "Esta semana": round(c.weekly.get(semana, 0.0), 2),
        "Promedio resto": round(sum(c.weekly.values()) / max(1, len(c.weekly)), 2),
    } for c in cands]).sort_values("Promedio resto", ascending=False))
if "FALLOS_NOTAS" in globals() and FALLOS_NOTAS:
    print(f"⚠ WAIVERS INCOMPLETO: fallaron {len(FALLOS_NOTAS)} notas de Yahoo. No confíes en un \"no pujes\"; espera 1 hora y vuelve a correr 3, 3b y 6.")

Waivers semana 8: no pujes

Waivers semana 8 · modo: solo sugerencias (no toca Yahoo)
Saldo FAAB: $74 · el rival con más saldo tiene $100
Pujas ganadoras recientes en tu liga: $1, $1, $1, $5, $6, $12, $12
Ningún jugador disponible mejora tus titulares lo suficiente para gastar FAAB. No pujes por titulares (mira abajo las mejoras de banca).
https://football.fantasysports.yahoo.com/f1/43220/players?status=A

                Jugador  Pos Equipo  Disponible  Esta semana  Promedio resto
2        Justin Herbert   QB    LAC          FA        14.49           17.97
5        Baker Mayfield   QB     TB          FA        18.90           17.04
1           Sam Darnold   QB    SEA          FA        19.04           16.76
0          Kirk Cousins   QB     LV          FA        17.93           16.32
3              Cam Ward   QB    TEN          FA        13.59           15.95
4          Daniel Jones   QB    IND  W (Oct 31)        12.78           15.87
6          Tanner McKee   QB    PHI          FA        13.64           14.99
7         J.J. McCarthy   QB    NYG          FA         0.00           13.87
51      Harrison Butker    K     KC          FA         8.79            9.16
9       Shedeur Sanders   QB    CLE          FA         0.00            9.05
49           Tyler Loop    K    BAL          FA         8.73            8.28
48             Matt Gay    K     LV          FA         8.78            7.84
52        Dominic Zvada    K    NYG          FA         0.00            7.55
50          Chad Ryland    K    ARI          FA         8.84            7.37
24         Keenan Allen   WR    IND  W (Oct 31)         6.55            7.13
25        Ryan Flournoy   WR    DAL  W (Oct 29)         7.83            6.79
31     Quentin Johnston   WR    LAC          FA         5.77            6.55
28      Kendrick Bourne   WR    ARI          FA         7.40            6.12
36         Mike Gesicki   TE    CIN          FA         6.48            5.90
13      Keaton Mitchell   RB    LAC          FA         5.03            5.85
40         Greg Dulcich   TE    MIA          FA         4.48            5.69
14        Samaje Perine   RB    CIN          FA         6.29            5.62
15         Kimani Vidal   RB    LAC          FA         5.67            5.59
41            AJ Barner   TE    SEA          FA         7.45            5.58
26      DeMario Douglas   WR     NE          FA         6.90            5.56
54              Packers  DEF     GB          FA         6.06            5.50
39         Tyler Higbee   TE    LAR  W (Oct 31)         6.67            5.47
55               Browns  DEF    CLE  W (Oct 31)         6.20            5.40
56                49ers  DEF     SF          FA         0.00            5.37
38        Darren Waller   TE    CAR          FA         5.47            5.34
19         Tyjae Spears   RB    TEN          FA         4.65            5.30
37        Michael Mayer   TE     LV          FA         5.68            5.27
30       Rashid Shaheed   WR    SEA          FA         4.25            5.22
57              Falcons  DEF    ATL          FA         5.71            5.14
17     Devin Singletary   RB    NYG          FA         0.00            5.11
42         Kenyon Sadiq   TE    NYJ          FA         6.92            5.10
18  Chris Rodriguez Jr.   RB    JAX          FA         5.87            5.00
16       Kenny Gainwell   RB     TB  W (Oct 29)         6.07            4.99
35          Tre' Harris   WR    LAC          FA         3.32            4.96
53           Buccaneers  DEF     TB          FA         5.59            4.91
27          Jaylin Noel   WR    HOU          FA         0.00            4.80
33       Malachi Fields   WR    NYG          FA         0.00            4.78
29     Dontayvion Wicks   WR    PHI          FA         3.53            4.66
21           Ty Johnson   RB    BUF          FA         4.57            4.60
32         Jahan Dotson   WR    ATL          FA         4.96            4.59
34       Rashod Bateman   WR    BAL          FA         4.93            4.50
20         Justice Hill   RB    BAL          FA         5.51            4.46
43   Darnell Washington   TE    PIT          FA         4.94            4.30
8           Jaxson Dart   QB    NYG          FA         0.00            4.26
47       Oronde Gadsden   TE    LAC          FA         3.18            3.95
44          Eli Raridon   TE     NE          FA         5.25            3.73
45        Tommy Tremble   TE    CAR          FA         3.52            3.70
22        Kendre Miller   RB     NO          FA         0.00            3.50
46            Noah Fant   TE     NO          FA         0.00            3.32
12       Emanuel Wilson   RB    SEA          FA         6.83            3.24
23     Tyrone Tracy Jr.   RB    NYG          FA         0.00            2.75
10          Jalen Hurts   QB    PHI          FA         0.00            0.00
11       Jameis Winston   QB    NYG          FA         0.00            0.00

In [ ]:
# ===== CELDA 7d (versión 3): PROYECCIONES AJUSTADAS CON LO QUE YA PASÓ (aprendizaje automático) =====
# Versión 3 (20 oct): solo guarda semanas terminadas, relee la última (correcciones de Yahoo),
# guarda equipo NFL y estado (para la celda 6c), exige mejora estadísticamente clara y mide
# la variación con errores fuera de muestra.
# Versión 2: pendientes limitadas (sin el error de los pateadores), pateador y defensa solo corrigen
# el promedio, y el ajuste se usa solo si mejora al menos 2%.
# Pégala debajo de la celda anti-bloqueo (y de la 7c si la usas). Córrela el martes.
#
# Qué hace, paso a paso:
#   1. HISTORIAL: para cada equipo de la liga y cada semana ya jugada, lee la proyección
#      que Yahoo le dio a cada jugador y los puntos que de verdad hizo. Lo guarda en tu
#      Drive (historial_proyecciones.csv): la próxima vez solo lee las semanas nuevas.
#   2. APRENDE: busca en qué se equivoca Yahoo en ESTA liga:
#        a) por posición: "cuando Yahoo dice 10 a un corredor, en realidad sale X";
#        b) por jugador: quién supera o falla su proyección una y otra vez
#           (con "freno": un jugador con pocas semanas casi no se mueve).
#   3. SE EXAMINA A SÍ MISMO: predice cada semana usando solo las semanas anteriores
#      (como si no conociera el futuro) y compara su error con el de Yahoo.
#      Si no le gana a Yahoo, NO se usa y te lo dice.
#   4. NUEVAS PROYECCIONES para todos los equipos: mejor alineación de cada equipo,
#      Yahoo vs ajustada, y probabilidad de ganar de cada partido de la semana.
#   5. Si AJUSTAR_7C = True, la celda 7c usa estas proyecciones la próxima vez que la corras.
#
# Páginas de Yahoo: 2 por equipo por semana nueva (~24 por semana). La primera vez,
# con 5 semanas, son ~120 páginas: 10 a 15 minutos con la celda anti-bloqueo.

import math
import os

import time
import numpy as np
import pandas as pd
from fantasy_autopilot.nfl import norm_slot

# ---------------- ajustes ----------------
SEMANA_OBJETIVO = None    # None = la primera semana que falta por jugar
ULTIMA_SEMANA = 17
FRENO_POSICION = 40       # cuántas observaciones hacen falta para confiar en el ajuste de posición
FRENOS_JUGADOR = [1, 2, 3, 5, 8, 10**6]   # se prueban todos; 10**6 = sin ajuste por jugador
AJUSTAR_7C = True
MEJORA_MINIMA = 0.02     # el ajuste solo se usa si baja el error de Yahoo al menos 2%
BASICAS = ("QB", "RB", "WR", "TE", "K", "DEF")
FLEX_POS = {"W/R/T": ("RB", "WR", "TE"), "W/R": ("RB", "WR"), "W/T": ("WR", "TE"),
            "Q/W/R/T": ("QB", "RB", "WR", "TE")}

carpeta_7d = getattr(pilot.cfg, "state_dir", None) or "/content"
ARCHIVO = os.path.join(carpeta_7d, "historial_proyecciones.csv")

# ---------------- rosters actuales (reusa los de la 7c si existen) ----------------
S = pilot.week()
equipos = pilot.web.teams()
if "_ROSTERS_7C" not in globals():
    _ROSTERS_7C = {}

def cargar_7d(team_id):
    team_id = str(team_id)
    clave = (team_id, S)
    if clave not in _ROSTERS_7C or time.time() - _ROSTERS_7C[clave][2] > 1800:
        ros = pilot.load_roster(S, team_id=team_id)
        pilot.enrich(ros.players, S)
        inicio_ = pilot._weekly_for_roster(ros.players, S)
        _ROSTERS_7C[clave] = (ros, inicio_, time.time())
        print(f"  leído {ros.team_name or team_id}: {len(ros.players)} jugadores")
    return _ROSTERS_7C[clave][:2]

rosters = {str(t.team_id): cargar_7d(t.team_id) for t in equipos}
inicio = min(i for _, i in rosters.values())
OBJ = SEMANA_OBJETIVO or inicio
SEMANAS_FUT = list(range(OBJ, ULTIMA_SEMANA + 1))

# ---------------- 1. historial ----------------
hist = pd.read_csv(ARCHIVO, dtype={"pid": str, "team_id": str}) if os.path.exists(ARCHIVO) else pd.DataFrame()
if len(hist) and "nfl" not in hist.columns:
    print("El historial viejo no tiene equipo NFL: se vuelve a leer completo (una sola vez).")
    hist = pd.DataFrame()
ULTIMA_TERMINADA = S - 1          # solo semanas con todos sus partidos jugados
if len(hist):
    hist = hist[hist["semana"] < ULTIMA_TERMINADA]   # la última se relee: Yahoo corrige estadísticas
ya = set(zip(hist["team_id"], hist["semana"])) if len(hist) else set()
nuevas = []
for w in range(1, ULTIMA_TERMINADA + 1):
    leidos = 0
    for t in equipos:
        tid = str(t.team_id)
        if (tid, w) in ya:
            continue
        leidos += 1
        _, tp = pilot.web.team_page(team_id=tid, week=w)
        reales = pilot.web.team_points(team_id=tid, week=w)
        for r in tp.rows:
            if r.proj is None or r.pid not in reales:
                continue
            nuevas.append({"semana": w, "team_id": tid, "equipo": t.name, "pid": str(r.pid),
                           "jugador": r.name, "pos": (r.positions or [""])[0],
                           "puesto": r.slot, "proy": float(r.proj), "real": float(reales[r.pid]),
                           "nfl": r.team, "estado": r.status})
    if leidos:
        print(f"  semana {w}: leídos {leidos} equipos")
if nuevas or len(hist):
    nuevo = pd.DataFrame(nuevas) if nuevas else pd.DataFrame(columns=hist.columns)
    # control: si Yahoo ya no guarda la proyección vieja, proy == real casi siempre
    for w, g in nuevo.groupby("semana"):
        if len(g) > 20 and (np.isclose(g["proy"], g["real"]).mean() > 0.8):
            raise RuntimeError(f"Semana {w}: Yahoo muestra los puntos reales en lugar de la proyección "
                               "vieja. Con esta página no se puede aprender. Avísame.")
    hist = pd.concat([hist, nuevo], ignore_index=True)
    hist.to_csv(ARCHIVO, index=False)
hist = hist[hist["pos"].isin(BASICAS) & (hist["proy"] > 0)].copy()
print(f"\nHistorial: {len(hist)} observaciones (jugador-semana con proyección > 0), "
      f"semanas {hist['semana'].min()} a {hist['semana'].max()}, guardado en {ARCHIVO}")

# ---------------- 2. el modelo ----------------
def ajuste_posicion(df):
    """Por posición: real = a + b * proy, frenado hacia a=0, b=1 (Yahoo) cuando hay pocos datos."""
    coef = {}
    for pos in BASICAS:
        g = df[df["pos"] == pos]
        n = len(g)
        if n < 8 or g["proy"].std() == 0:
            coef[pos] = (0.0, 1.0, n)
            continue
        peso = n / (n + FRENO_POSICION)
        if pos in ("K", "DEF"):
            # pateadores y defensas: sus proyecciones casi no varían; solo se corrige el promedio
            coef[pos] = (peso * float((g["real"] - g["proy"]).mean()), 1.0, n)
            continue
        b, a = np.polyfit(g["proy"], g["real"], 1)
        b = float(np.clip(b, 0.6, 1.4))                 # pendiente razonable, sin inventos
        a = float(g["real"].mean() - b * g["proy"].mean())
        coef[pos] = (peso * a, 1 + peso * (b - 1), n)
    return coef

def predecir_pos(coef, pos, proy):
    a, b, _ = coef.get(pos, (0.0, 1.0, 0))
    return np.maximum(0.0, a + b * np.asarray(proy, dtype=float))

def sesgo_jugador(df, coef, freno):
    base = np.array([predecir_pos(coef, p, x) for p, x in zip(df["pos"], df["proy"])], dtype=float)
    r = df["real"].to_numpy() - base
    g = pd.DataFrame({"pid": df["pid"], "r": r}).groupby("pid")["r"]
    return (g.sum() / (g.count() + freno)).to_dict()

def predecir(df, coef, sesgo):
    base = np.array([predecir_pos(coef, p, x) for p, x in zip(df["pos"], df["proy"])], dtype=float)
    return np.maximum(0.0, base + df["pid"].map(sesgo).fillna(0.0).to_numpy())

# ---------------- 3. examen honesto (solo con semanas anteriores) ----------------
semanas_h = sorted(hist["semana"].unique())
filas_cv, errores = [], {f: [] for f in FRENOS_JUGADOR}
err_yahoo, err_pos = [], []
residuos_fuera = {f: [] for f in FRENOS_JUGADOR}
err_anidado, res_anidado = [], []
for w in semanas_h[2:]:
    residuos_semana = {}
    tr, te = hist[hist["semana"] < w], hist[hist["semana"] == w]
    c = ajuste_posicion(tr)
    e_y = np.abs(te["real"] - te["proy"]).mean()
    e_p = np.abs(te["real"] - np.array([predecir_pos(c, p, x) for p, x in zip(te["pos"], te["proy"])])).mean()
    fila = {"Semana examinada": w, "Datos para aprender": len(tr), "Error Yahoo": round(e_y, 2),
            "Error ajuste por posición": round(e_p, 2)}
    err_yahoo.append(e_y)
    err_pos.append(e_p)
    for f in FRENOS_JUGADOR:
        r_out = te["real"].to_numpy() - predecir(te, c, sesgo_jugador(tr, c, f))
        errores[f].append(np.abs(r_out).mean())
        residuos_fuera[f] += list(zip(te["pos"], r_out))
        residuos_semana[f] = list(zip(te["pos"], r_out))
    # el freno se elige SOLO con las semanas de examen anteriores (nunca mirando esta semana)
    previas = len(errores[FRENOS_JUGADOR[0]]) - 1
    f_sem = (min(FRENOS_JUGADOR, key=lambda f: np.mean(errores[f][:previas])) if previas
             else max(FRENOS_JUGADOR))
    err_anidado.append(errores[f_sem][-1])
    res_anidado += residuos_semana[f_sem]
    fila["Error ajuste completo"] = round(errores[f_sem][-1], 2)
    filas_cv.append(fila)

if not filas_cv:
    raise RuntimeError("Hacen falta al menos 3 semanas jugadas para examinar el modelo.")
FRENO = min(FRENOS_JUGADOR, key=lambda f: np.mean(errores[f]))   # para usar de aquí en adelante
# el examen usa el freno elegido semana a semana sin mirar el futuro (elegirlo con todas las semanas y luego
# examinarlo con las mismas sería hacer trampa a favor del modelo)
e_yahoo, e_modelo = np.mean(err_yahoo), np.mean(err_anidado)
dif = np.array(err_yahoo) - np.array(err_anidado)          # mejora semana por semana
error_std = dif.std(ddof=1) / np.sqrt(len(dif)) if len(dif) > 1 else float("inf")
USAR = bool(dif.mean() > MEJORA_MINIMA * e_yahoo and dif.mean() > 2 * error_std)
print("\nEXAMEN: error promedio por jugador (puntos), prediciendo cada semana solo con las anteriores")
display(pd.DataFrame(filas_cv))
print(f"Promedio: Yahoo {e_yahoo:.2f} · ajuste {e_modelo:.2f} "
      f"({(e_yahoo - e_modelo) / e_yahoo * 100:+.1f}% de mejora) · freno por jugador elegido: "
      f"{'sin ajuste por jugador' if FRENO >= 10**6 else FRENO}")
print("RESULTADO:", "el ajuste le gana a Yahoo y se usa." if USAR else
      f"el ajuste no le gana a Yahoo de forma clara (al menos {MEJORA_MINIMA:.0%} y más que la suerte entre "
      f"semanas, ±{2 * error_std:.2f}): se siguen usando las proyecciones de Yahoo.")

# modelo final con todo el historial
COEF = ajuste_posicion(hist)
SESGO = sesgo_jugador(hist, COEF, FRENO) if USAR else {}
if not USAR:
    COEF = {pos: (0.0, 1.0, 0) for pos in BASICAS}
# variación medida con errores FUERA de muestra (no sobreestima la confianza)
_res = res_anidado if USAR else list(zip(hist["pos"], hist["real"] - hist["proy"]))
DESV = {pos: float(np.std([r for p_, r in _res if p_ == pos]) or 6.0) for pos in BASICAS}

print("\nCALIBRACIÓN POR POSICIÓN (en esta liga)")
display(pd.DataFrame([{
    "Posición": pos, "Datos": COEF[pos][2] if USAR else int((hist['pos'] == pos).sum()),
    "Yahoo dice 5": round(float(predecir_pos(COEF, pos, 5)), 2),
    "Yahoo dice 10": round(float(predecir_pos(COEF, pos, 10)), 2),
    "Yahoo dice 20": round(float(predecir_pos(COEF, pos, 20)), 2),
    "Promedio real - Yahoo": round(float((hist.loc[hist['pos'] == pos, 'real'] - hist.loc[hist['pos'] == pos, 'proy']).mean()), 2),
    "Variación típica (±)": round(DESV[pos], 1),
} for pos in BASICAS]))

if USAR and FRENO < 10**6:
    g = hist.assign(dif=hist["real"] - hist["proy"]).groupby(["pid", "jugador"]).agg(
        semanas=("dif", "size"), dif=("dif", "mean")).reset_index()
    g["ajuste por semana"] = g["pid"].map(SESGO).round(2)
    g = g[g["semanas"] >= 3]
    print("\nJUGADORES QUE MÁS SUPERAN SU PROYECCIÓN (3+ semanas)")
    display(g.sort_values("ajuste por semana", ascending=False).head(10)[["jugador", "semanas", "dif", "ajuste por semana"]])
    print("JUGADORES QUE MÁS FALLAN SU PROYECCIÓN (3+ semanas)")
    display(g.sort_values("ajuste por semana").head(10)[["jugador", "semanas", "dif", "ajuste por semana"]])

# ---------------- 4. nuevas proyecciones para todos ----------------
def ajustar(p, w):
    v = p.weekly.get(w, 0.0) if not hasattr(p, "weekly_yahoo") else p.weekly_yahoo.get(w, 0.0)
    if v <= 0 or p.position not in BASICAS:
        return 0.0
    return float(max(0.0, predecir_pos(COEF, p.position, v) + SESGO.get(str(p.pid), 0.0)))

ejemplo = next(iter(rosters.values()))[0]
SLOTS = [norm_slot(s) for s in ejemplo.slots]
DED = {pos: SLOTS.count(pos) for pos in BASICAS}
FLX = [s for s in SLOTS if s not in BASICAS]
FP = FLEX_POS.get(FLX[0], ()) if FLX else ()

def mejor(jugadores, valor):
    """Mejor alineación con los puntos de valor(p): devuelve (total, titulares)."""
    total, tit, sobran = 0.0, [], []
    for pos in BASICAS:
        orden = sorted((p for p in jugadores if p.position == pos), key=valor, reverse=True)
        tit += orden[:DED[pos]]
        total += sum(valor(p) for p in orden[:DED[pos]])
        if pos in FP:
            sobran += orden[DED[pos]:]
    flex = sorted(sobran, key=valor, reverse=True)[:len(FLX)]
    return total + sum(valor(p) for p in flex), tit + flex

def yahoo_w(w):
    return lambda p: (p.weekly_yahoo if hasattr(p, "weekly_yahoo") else p.weekly).get(w, 0.0)

def ajust_w(w):
    return lambda p: ajustar(p, w)

nombres_eq = {str(t.team_id): f"{t.name} ({t.manager})" for t in equipos}
tabla, sigma_eq = [], {}
for tid, (ros, _) in rosters.items():
    js = [p for p in ros.players if p.position in BASICAS and p.slot != "IR"]
    y_obj, _ = mejor(js, yahoo_w(OBJ))
    a_obj, tit = mejor(js, ajust_w(OBJ))
    sigma_eq[tid] = math.sqrt(sum(DESV[p.position] ** 2 for p in tit))
    y_ros = np.mean([mejor(js, yahoo_w(w))[0] for w in SEMANAS_FUT])
    a_ros = np.mean([mejor(js, ajust_w(w))[0] for w in SEMANAS_FUT])
    tabla.append({"Equipo": nombres_eq.get(tid, tid), f"Yahoo semana {OBJ}": round(y_obj, 1),
                  f"Ajustada semana {OBJ}": round(a_obj, 1), "Yahoo resto (pts/sem)": round(y_ros, 1),
                  "Ajustada resto (pts/sem)": round(a_ros, 1), "_tid": tid})
tabla_eq = pd.DataFrame(tabla).sort_values("Ajustada resto (pts/sem)", ascending=False)
print(f"\nNUEVAS PROYECCIONES: mejor alineación de cada equipo (semana {OBJ} y promedio semanas {OBJ}-{ULTIMA_SEMANA})")
display(tabla_eq.drop(columns="_tid"))

try:
    partidos = pilot.web.matchups(OBJ)
except Exception as exc:  # noqa: BLE001
    partidos = []
    print("No pude leer los partidos de la semana:", exc)
filas_p = []
ajust_por_id = dict(zip(tabla_eq["_tid"], tabla_eq[f"Ajustada semana {OBJ}"]))
for a, b in partidos:
    if a.team_id not in ajust_por_id or b.team_id not in ajust_por_id:
        continue
    pa, pb = ajust_por_id[a.team_id], ajust_por_id[b.team_id]
    s = math.sqrt(sigma_eq[a.team_id] ** 2 + sigma_eq[b.team_id] ** 2) or 1.0
    prob = 0.5 * (1 + math.erf((pa - pb) / (s * math.sqrt(2))))
    filas_p.append({"Equipo A": nombres_eq.get(a.team_id, a.name), "Ajustada A": pa,
                    "Equipo B": nombres_eq.get(b.team_id, b.name), "Ajustada B": pb,
                    "Prob. de ganar A": f"{prob:.0%}"})
if filas_p:
    print(f"\nPARTIDOS DE LA SEMANA {OBJ} con proyecciones ajustadas")
    display(pd.DataFrame(filas_p))

# ---------------- 5. que la 7c use lo ajustado ----------------
if not USAR:
    for ros, _ in rosters.values():
        for p in ros.players:
            if hasattr(p, "weekly_yahoo"):
                p.weekly = dict(p.weekly_yahoo)   # deshace un ajuste anterior
if AJUSTAR_7C and USAR:
    for ros, _ in rosters.values():
        for p in ros.players:
            if not hasattr(p, "weekly_yahoo"):
                p.weekly_yahoo = dict(p.weekly)
            p.weekly = {w: ajustar(p, w) for w in p.weekly_yahoo}
    print("\nListo: si ahora corres la celda 7c, usará las proyecciones ajustadas.")
pd.DataFrame([{"equipo": nombres_eq.get(tid, tid), "jugador": p.name, "pos": p.position,
               **{f"S{w} yahoo": round(yahoo_w(w)(p), 2) for w in SEMANAS_FUT[:3]},
               **{f"S{w} ajustada": round(ajustar(p, w), 2) for w in SEMANAS_FUT[:3]}}
              for tid, (ros, _) in rosters.items() for p in ros.players if p.position in BASICAS]
             ).to_csv(os.path.join(carpeta_7d, "proyecciones_ajustadas.csv"), index=False)
print("Guardé proyecciones_ajustadas.csv en", carpeta_7d)


# ---------------- 6. variación de cada jugador y descuento real de "Questionable" ----------------
# a) Cuánto se aleja cada jugador de su proyección (frenado hacia su posición). La celda 4 lo usa para
#    elegir entre dos jugadores parecidos según te convenga arriesgar (vas abajo) o asegurar (vas arriba).
# b) El descuento de un "Questionable" se mide con lo que de verdad pasó. El cuaderno guarda el estado
#    de cada jugador antes del partido (estado_log.csv); aquí se compara con los puntos reales.
from fantasy_autopilot import calibration as _cal
from pathlib import Path
pilot.cfg.player_sd = _cal.player_sd(hist.rename(columns={"proy": "proj"}).to_dict("records"), DESV)
print(f"\nVariación por jugador guardada para {len(pilot.cfg.player_sd)} jugadores (3 semanas o más).")
_log = _cal.read_log(Path(os.path.expanduser(carpeta_7d)) / "estado_log.csv")
_reales = {(int(r.semana), str(r.pid)): float(r.real) for r in hist.itertuples()}
_q = _cal.questionable_factor(_log, _reales)
print("Descuento de Questionable:", _q["texto"])
if _q["raw"] is not None and _q["n"] >= 30:
    pilot.cfg.status_probs["Q"] = round(_q["factor"], 2)
    print(f"Desde ahora un titular Questionable vale su proyección × {pilot.cfg.status_probs['Q']}.")
else:
    print("Se sigue usando 0.75 hasta tener 30 casos.")

# Separar "no jugó" de "jugó limitado" con la participación real (snaps y toques de Sleeper)
_sem_log = sorted({int(r["week"]) for r in _log if str(r.get("week", "")).isdigit()} & set(int(x) for x in hist["semana"].unique()))
_stats = {}
if getattr(pilot, "sleeper", None) is not None and hasattr(pilot.sleeper, "weekly_stats"):
    for _w in sorted(set(_sem_log) | {w - k for w in _sem_log for k in (1, 2, 3) if w - k >= 1}):
        try:
            _stats[_w] = pilot.sleeper.weekly_stats(pilot.season(), _w)
        except Exception as exc:  # noqa: BLE001
            print(f"Sin estadísticas de Sleeper de la semana {_w}: {str(exc)[:60]}")
_qs = _cal.questionable_split(_log, _reales, _stats)
print("Questionable por partes:", _qs["texto"])
if _qs["n"] >= 30 and _qs["active_factor"] is not None:
    pilot.cfg.active_q_factor = round(max(0.5, min(1.0, _qs["active_factor"])), 2)
    print(f"Un Questionable que ya salió activo (una hora antes del partido) vale ahora × {pilot.cfg.active_q_factor}.")

# ---------------- 7. error por EQUIPO (lo que decide el partido) y control de Yahoo ----------------
_tit = hist[~hist["puesto"].isin(["BN", "IR"])]
_eqw = _tit.groupby(["semana", "team_id"]).agg(proy=("proy", "sum"), real=("real", "sum")).reset_index()
_eqw["dif"] = _eqw["real"] - _eqw["proy"]
print(f"\nError por EQUIPO (suma de titulares): ±{_eqw['dif'].std():.1f} pts por semana, "
      f"promedio {_eqw['dif'].mean():+.1f}, error típico {_eqw['dif'].abs().mean():.1f}.")
print("Por jugador el error parece chico (±5 a ±10), pero 9 titulares juntos suman ±20 a ±25 por semana.")
_mio = _eqw[_eqw["team_id"] == str(pilot.cfg.team_id)].sort_values("semana")
if len(_mio):
    display(pd.DataFrame({"Semana": _mio["semana"], "Yahoo proyectó": _mio["proy"].round(2),
                          "Hiciste": _mio["real"].round(2), "Diferencia": _mio["dif"].round(2)}))
# ¿Yahoo cambia la proyección guardada después del partido? Se compara con la foto de antes del partido.
_snap = _cal.last_snapshots(_log)
_cmp = [(float(r.proy) - float(_snap[k]["proj"]), float(r.real) - float(_snap[k]["proj"]))
        for r in hist.itertuples() for k in [(int(r.semana), str(r.pid))] if k in _snap]
if len(_cmp) >= 15:
    _a = np.array(_cmp)
    _corr = float(np.corrcoef(_a[:, 0], _a[:, 1])[0, 1]) if _a[:, 0].std() > 0 else 0.0
    print(f"Control con {len(_cmp)} fotos de antes del partido: la proyección guardada se movió en promedio "
          f"{np.abs(_a[:, 0]).mean():.2f} pts; relación con el resultado real: {_corr:+.2f}.")
    if np.abs(_a[:, 0]).mean() > 2 and _corr > 0.5:
        print("⚠ Yahoo SÍ cambia la proyección después del partido: el examen de arriba es demasiado optimista. "
              "Desde ahora se usan solo las fotos de antes del partido (estado_log.csv).")
    else:
        print("✓ La proyección guardada es la de antes del partido: el examen de arriba es honesto.")
else:
    print("Control de Yahoo: todavía no hay fotos de antes del partido de semanas terminadas "
          "(se juntan solas cada vez que corres la celda 4 o la 8).")

# ---------------- 8. auditoría de cada semana: ¿mala suerte, error de alineación o falta de roster? ----------------
from fantasy_autopilot.audit import week_audit
_SL = [s for s in roster.slots] if "roster" in globals() else ["QB", "WR", "WR", "RB", "RB", "TE", "W/R/T", "K", "DEF"]
_hall = pd.read_csv(ARCHIVO, dtype={"pid": str, "team_id": str})   # incluye a los de proyección 0
_fav, _fav_gana, _aud = 0, 0, []
for _w in sorted(_hall["semana"].unique()):
    try:
        _pares = pilot.web.matchups(int(_w))
    except Exception as exc:  # noqa: BLE001
        print(f"Semana {_w}: no pude leer los partidos ({str(exc)[:60]})")
        continue
    _tot = _hall[(_hall["semana"] == _w) & ~_hall["puesto"].isin(["BN", "IR"])].groupby("team_id")["proy"].sum()
    for _a, _b in _pares:
        if (getattr(_a, "score", None) is None or getattr(_b, "score", None) is None
                or _a.team_id not in _tot or _b.team_id not in _tot):
            continue
        if abs(_tot[_a.team_id] - _tot[_b.team_id]) > 0.01:
            _fav += 1
            _fav_gana += (_tot[_a.team_id] > _tot[_b.team_id]) == (_a.score > _b.score)
        for _yo, _el in ((_a, _b), (_b, _a)):
            if _yo.team_id == str(pilot.cfg.team_id):
                _au = week_audit(_hall[(_hall["team_id"] == _yo.team_id) & (_hall["semana"] == _w)].to_dict("records"),
                                 _SL, opponent=_el.score)
                _aud.append({"Semana": int(_w), "Hiciste": round(_au.scored, 2), "Rival": round(_el.score, 2),
                             "Proy. jugada": round(_au.proj_used, 2), "Mejor proy. posible": round(_au.proj_best, 2),
                             "Perfecta (sabiendo el resultado)": round(_au.perfect, 2),
                             "Entraban": ", ".join(f"{n} {v:.1f}" for n, v in _au.came_in) or "—",
                             "Salían": ", ".join(f"{n} {v:.1f}" for n, v in _au.went_out) or "—",
                             "Veredicto": _au.verdict()})
if _aud:
    print("\nAUDITORÍA DE TUS SEMANAS")
    print("  Mejor proy. posible > Proy. jugada  = error evitable (se pudo saber antes del partido).")
    print("  Perfecta < Rival                    = ningún cambio de alineación ganaba: mala suerte o falta de roster.")
    display(pd.DataFrame(_aud))
if _fav:
    print(f"\nEl equipo con más puntos proyectados ganó {_fav_gana} de {_fav} partidos ({_fav_gana / _fav:.0%}). "
          "Por eso las probabilidades de ganar son estimaciones, no garantías.")

  leído Traffic Safety - 0-17: 16 jugadores
  leído Traffic Safety - At least I'm not Dallas: 16 jugadores
  leído Traffic Safety - Better Luck NextYear: 15 jugadores
  leído Traffic Safety - End Zone Hunters: 16 jugadores
  leído Traffic Safety - Fahim n Furious: 16 jugadores
  leído Traffic Safety - Fourth Quarter Delio: 18 jugadores
  leído Traffic Safety - Guap Goblin: 15 jugadores
  leído Traffic Safety - Mountain Drew: 18 jugadores
  leído Traffic Safety - Mountain Top: 16 jugadores
  leído Traffic Safety - Riddle Renegades: 16 jugadores
  leído Traffic Safety - Silly Old Sawyer: 16 jugadores
  leído Traffic Safety - T-Law & Fornication: 18 jugadores
  semana 7: leídos 12 equipos

Historial: 1161 observaciones (jugador-semana con proyección > 0), semanas 1 a 7, guardado en /content/drive/MyDrive/fantasy_autopilot/historial_proyecciones.csv

EXAMEN: error promedio por jugador (puntos), prediciendo cada semana solo con las anteriores

,Semana examinada,Datos para aprender,Error Yahoo,Error ajuste por posición,Error ajuste completo
0,3,365,5.04,4.91,4.91
1,4,536,5.24,5.36,5.36
2,5,705,5.75,5.74,5.74
3,6,863,5.06,5.20,5.20
4,7,1012,5.33,5.34,5.34

Promedio: Yahoo 5.28 · ajuste 5.31 (-0.5% de mejora) · freno por jugador elegido: sin ajuste por jugador
RESULTADO: el ajuste no le gana a Yahoo de forma clara (al menos 2% y más que la suerte entre semanas, ±0.10): se siguen usando las proyecciones de Yahoo.

CALIBRACIÓN POR POSICIÓN (en esta liga)

,Posición,Datos,Yahoo dice 5,Yahoo dice 10,Yahoo dice 20,Promedio real - Yahoo,Variación típica (±)
0,QB,150,5.0,10.0,20.0,-0.21,9.3
1,RB,304,5.0,10.0,20.0,0.01,6.8
2,WR,368,5.0,10.0,20.0,-0.43,6.7
3,TE,143,5.0,10.0,20.0,-0.14,6.2
4,K,89,5.0,10.0,20.0,0.42,5.2
5,DEF,107,5.0,10.0,20.0,-0.52,4.9

NUEVAS PROYECCIONES: mejor alineación de cada equipo (semana 8 y promedio semanas 8-17)

,Equipo,Yahoo semana 8,Ajustada semana 8,Yahoo resto (pts/sem),Ajustada resto (pts/sem)
1,At least I'm not Dallas (JOSHUA),112.6,112.6,121.8,121.8
10,Silly Old Sawyer (mike),102.2,102.2,117.1,117.1
5,Fourth Quarter Delio (Delio),104.6,104.6,113.7,113.7
4,Fahim n Furious (Fahim),102.7,102.7,110.9,110.9
3,End Zone Hunters (Douglas),109.4,109.4,109.6,109.6
9,Riddle Renegades (Keith),112.5,112.5,108.6,108.6
2,Better Luck NextYear (Ron),104.1,104.1,105.1,105.1
7,Mountain Drew (Drew Commissioner),96.1,96.1,104.8,104.8
8,Mountain Top (Tito),103.0,103.0,104.5,104.5
0,0-17 (Gregg),100.8,100.8,104.4,104.4
11,T-Law & Fornication (Preston),99.0,99.0,103.7,103.7
6,Guap Goblin (Brian),95.0,95.0,102.3,102.3

PARTIDOS DE LA SEMANA 8 con proyecciones ajustadas

,Equipo A,Ajustada A,Equipo B,Ajustada B,Prob. de ganar A
0,Fourth Quarter Delio (Delio),104.6,Mountain Drew (Drew Commissioner),96.1,62%
1,Better Luck NextYear (Ron),104.1,Mountain Top (Tito),103.0,52%
2,Guap Goblin (Brian),95.0,End Zone Hunters (Douglas),109.4,31%
3,Silly Old Sawyer (mike),102.2,0-17 (Gregg),100.8,52%
4,At least I'm not Dallas (JOSHUA),112.6,T-Law & Fornication (Preston),99.0,68%
5,Riddle Renegades (Keith),112.5,Fahim n Furious (Fahim),102.7,64%

Guardé proyecciones_ajustadas.csv en /content/drive/MyDrive/fantasy_autopilot

Variación por jugador guardada para 197 jugadores (3 semanas o más).
Descuento de Questionable: 2 casos Q: jugaron 2/2. Real ÷ proyección: 1.14 contra 0.71 de los sanos → factor medido 1.60; con freno hacia 0.75: 0.80. Yahoo ya descuenta a estos jugadores: multiplicar otra vez sería doble descuento.
Se sigue usando 0.75 hasta tener 30 casos.
Questionable por partes: 2 casos Q con participación conocida (faltan 28 para separar 'no jugó' de 'jugó limitado').

Error por EQUIPO (suma de titulares): ±23.4 pts por semana, promedio -2.2, error típico 19.2.
Por jugador el error parece chico (±5 a ±10), pero 9 titulares juntos suman ±20 a ±25 por semana.

    Semana  Yahoo proyectó  Hiciste  Diferencia
4        1          110.72   106.30       -4.42
16       2           79.86    63.48      -16.38
28       3          106.83   116.38        9.55
40       4          121.03   151.32       30.29
52       5          121.94   175.46       53.52
64       6          119.78    79.36      -40.42
76       7          121.99    88.92      -33.07

Control con 26 fotos de antes del partido: la proyección guardada se movió en promedio 0.05 pts; relación con el resultado real: +0.17.
✓ La proyección guardada es la de antes del partido: el examen de arriba es honesto.

AUDITORÍA DE TUS SEMANAS
  Mejor proy. posible > Proy. jugada  = error evitable (se pudo saber antes del partido).
  Perfecta < Rival                    = ningún cambio de alineación ganaba: mala suerte o falta de roster.

,Semana,Hiciste,Rival,Proy. jugada,Mejor proy. posible,Perfecta (sabiendo el resultado),Entraban,Salían,Veredicto
0,1,106.30,131.94,110.72,112.93,106.30,—,—,perdiste por 25.64 y ni la alineación perfecta...
1,2,63.48,110.72,79.86,98.24,91.18,"Bhayshul Tuten 13.2, Xavier Worthy 11.0, Tyjae...","Lions -2.0, Puka Nacua 0.0, Nico Collins 0.0, ...",perdiste por 47.24 y ni la alineación perfecta...
2,3,116.38,96.98,106.83,106.83,118.08,Rashod Bateman 4.7,Xavier Worthy 3.0,ganaste.
3,4,151.32,124.66,121.03,121.03,162.32,"Spencer Shrader 17.4, Bhayshul Tuten 10.1","Cam Skattebo 7.1, Tyler Loop 9.4",ganaste.
4,5,175.46,71.38,121.94,121.94,183.66,"Denzel Boston 12.1, Brenton Strange 10.3","Cam Skattebo 6.1, Nico Collins 8.1",ganaste.
5,6,79.36,103.82,119.78,119.78,92.96,"Keenan Allen 12.2, Xavier Worthy 10.8","Cam Skattebo 0.0, Nico Collins 9.4",perdiste por 24.46 y ni la alineación perfecta...
6,7,88.92,87.52,121.99,122.62,106.72,"Cam Skattebo 18.6, Malik Washington 5.0","Nico Collins 1.6, Denzel Boston 4.2",ganaste.

El equipo con más puntos proyectados ganó 34 de 42 partidos (81%). Por eso las probabilidades de ganar son estimaciones, no garantías.

In [ ]:
#@title 7e. Proyección propia contra Yahoo (examen con tus semanas pasadas) { display-mode: "form" }
#@markdown **La proyección propia es la que usan las celdas 4, 5, 5b, 5d, 6 y 8** (en QB, RB, WR y TE; pateador y
#@markdown defensa siguen con Yahoo porque Sleeper los puntúa distinto). Cómo se hace:
#@markdown 1. Parte de la proyección de Sleeper convertida a la puntuación de tu liga (TD de pase 6, intercepción −2:
#@markdown    se aprende sola comparando con los puntos que Yahoo te dio).
#@markdown 2. La corrige un modelo (regresión ridge) entrenado con cada partido de la NFL desde la temporada pasada
#@markdown    (~9,000): cómo viene rindiendo el jugador contra su proyección, sus snaps, targets y acarreos contra lo
#@markdown    proyectado, cuánto permite el rival a su posición y la línea de apuestas (puntos esperados de su equipo).
#@markdown **Examen honesto:** cada semana pasada se predice con un modelo entrenado solo con semanas anteriores y se
#@markdown compara con lo que Yahoo proyectó en los partidos de tu liga (páginas de partido). Si pierde, se usa Yahoo.
#@markdown Datos del examen: el historial de la **7d** (todos los equipos, todas las semanas) si la corriste; si no,
#@markdown las páginas de partido de Yahoo (~6 por semana). La primera vez baja datos de Sleeper (2–4 minutos).
_filas_7e = None
if "hist" in globals() and len(hist):
    from fantasy_autopilot.history import from_records
    _filas_7e = from_records(hist.to_dict("records"))
    print(f"Examen con el historial de la 7d: {len(_filas_7e)} jugador-semanas de toda la liga.")
r_examen = pilot.run("projection_exam", rows=_filas_7e)
print(r_examen.title, "\n")
print(r_examen.text)

Examen con el historial de la 7d: 1161 jugador-semanas de toda la liga.
Proyección propia: error 5.38 vs Yahoo 5.41

EXAMEN de la proyección propia (semanas pasadas de tu liga, 1161 jugador-semanas leídas).
Cada semana se predijo con un modelo entrenado SOLO con semanas anteriores, como en la vida real.
Posiciones con proyección propia: QB, RB, WR, TE (K y DEF siguen con Yahoo).
Semana | jugadores | error Yahoo | error propia | (toda la NFL: Sleeper → propia)
  S1    186        5.97         5.90        (4.43 → 4.33, 389 jugadores)
  S2    179        5.51         5.43        (4.02 → 4.00, 396 jugadores)
  S3    171        5.04         4.97        (4.21 → 4.19, 403 jugadores)
  S4    169        5.24         5.28        (3.87 → 3.89, 381 jugadores)
  S5    158        5.75         5.77        (4.25 → 4.26, 363 jugadores)
  S6    149        5.06         5.04        (4.13 → 4.08, 340 jugadores)
  S7    149        5.33         5.29        (4.10 → 4.13, 336 jugadores)
Promedio: Yahoo 5.41 · propia 5.38 pts de error por jugador (-0.6%)
Decisiones titular/banca (pares de la misma posición y semana, 20314): Yahoo acierta 65% · propia 65%
Tus alineaciones elegidas con cada proyección (puntos reales): Yahoo 792.9 · propia 776.3 · perfecta (sabiendo el futuro) 861.2
Puntuación de tu liga aprendida (sobre la de Sleeper): TD de pase +2, intercepción -1
Jugadores tuyos que Yahoo proyecta mal una y otra vez (el modelo ya lo toma en cuenta):
  • Daniel Jones: 6 de 6 semanas por debajo de Yahoo, promedio -7.1 pts
  • Kenny Gainwell: 5 de 6 semanas por debajo de Yahoo, promedio -3.5 pts
DECISIÓN: se usa la proyección propia en alineación, rival, waivers y piloto.
Límite real: un partido es en gran parte suerte. Ni sabiendo el promedio real de cada jugador se baja de ~5 pts de error; las mejores proyecciones ganan por décimas, y esas décimas se notan en muchas decisiones a lo largo de la temporada.

In [ ]:
#@title 6c. Inteligencia de la liga: qué necesita cada equipo, qué hará y a quién bloquear { display-mode: "form" }
#@markdown Córrela el **martes**. Lee las páginas de partido de las semanas pasadas (se guardan; la primera vez tarda). Lee la clasificación, los movimientos
#@markdown de toda la temporada y el roster de cada equipo para la próxima semana. Luego:
#@markdown 1. **Necesidades**: huecos de cada equipo (descansos, lesiones) y su posición más débil.
#@markdown 2. **Perfil de cada manager**: cuánto se mueve, cuánto puja, qué posiciones busca, si llena sus huecos.
#@markdown 3. **Examen honesto**: un modelo aprendido de la liga predice quién agrega y en qué posición; se
#@markdown    compara semana por semana con la regla vieja (que solo miraba descansos).
#@markdown 4. **Predicción** de quién va a pujar y en qué posición esta semana.
#@markdown 5. **Cómo juega cada manager** (pujas, altas que no usa) y **amenazas a tus pujas** de la celda 6.
#@markdown 6. **Mapa de trades**: quién tiene en la banca algo mejor que tu FLEX y qué le falta a él.
#@markdown 7. **Bloqueos**: jugadores libres que un equipo que va arriba de ti necesita, cuando el mejor libre
#@markdown    es claramente mejor que el segundo y quitárselo te cuesta poco.
SEMANA_6C = 0        #@param {type:"integer"}
GAP_MINIMO = 2.0     #@param {type:"number"}
#@markdown `SEMANA_6C = 0` usa la próxima semana. `GAP_MINIMO`: diferencia mínima (puntos) entre el mejor y el
#@markdown segundo mejor libre de esa posición para que valga la pena bloquear.
import io, os, re
from collections import Counter, defaultdict
from datetime import date
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from fantasy_autopilot.engine import projected_weekly
from fantasy_autopilot.nfl import norm_slot

# semanas de descanso de cada equipo NFL, del calendario de nflverse (respaldo: la lista fija)
BYES = {5: {"CAR", "KC"}, 6: {"CIN", "DET", "MIA", "MIN"}, 7: {"BUF", "JAX", "LAC", "WAS"},
        8: {"HOU", "NO", "NYG", "SF"}, 9: {"PIT", "TEN"}, 10: {"CHI", "DEN", "PHI", "TB"},
        11: {"ATL", "CLE", "GB", "LAR", "NE", "SEA"}, 12: set(), 13: {"BAL", "IND", "LV", "NYJ"},
        14: {"ARI", "DAL"}}
for _w in range(1, 19):
    try:
        _b = pilot._bye_teams(_w)
    except Exception:  # noqa: BLE001
        _b = None
    if _b is not None:
        BYES[_w] = set(_b)
INICIO_TEMPORADA = date(2026, 9, 8)   # martes antes de la semana 1
BASICAS = ("QB", "RB", "WR", "TE", "K", "DEF")
INACTIVOS = {"O", "IR", "D", "PUP", "NFI", "SUSP", "NA"}
carpeta_6c = getattr(pilot.cfg, "state_dir", None) or "/content"
MI_ID = str(pilot.cfg.team_id)
S_ACT = pilot.week()
W = SEMANA_6C or pilot._target_week()   # el martes Yahoo ya marca la semana nueva: se prepara esa
equipos = pilot.web.teams()
nombre_eq = {str(t.team_id): t.name for t in equipos}
manager_eq = {str(t.team_id): t.manager for t in equipos}
faab_eq = {str(t.team_id): t.faab for t in equipos}
def semana_de(d):
    return 1 + (d - INICIO_TEMPORADA).days // 7

# ---------------- clasificación ----------------
rank = {}
try:
    for tabla in pd.read_html(io.StringIO(pilot.web.league_home().html)):
        cols = [str(c) for c in tabla.columns]
        if any("W-L-T" in c for c in cols):
            col_eq = next(c for c in tabla.columns if "Team" in str(c))
            for i, fila in tabla.iterrows():
                txt = str(fila[col_eq])
                tid = next((k for k, n in sorted(nombre_eq.items(), key=lambda kv: -len(kv[1] or "")) if n and n in txt), None)
                if tid:
                    rank[tid] = int(re.sub(r"\D", "", str(fila[tabla.columns[0]])) or i + 1)
            break
except Exception as exc:  # noqa: BLE001
    print("No pude leer la clasificación:", exc)
if not rank:
    print("Sin clasificación: los bloqueos se calculan solo contra tu próximo rival.")
mi_rank = rank.get(MI_ID, 99)

# ---------------- movimientos de toda la temporada ----------------
from fantasy_autopilot.yahoo.parse import parse_transactions_full
from fantasy_autopilot.league import moves_table, manager_profiles, claim_threats
def leer_movimientos():
    """Todas las páginas de movimientos (25 por página). Cada jugador con su posición, acción y puja."""
    vistos, txs = set(), []
    for desde in range(0, 1500, 25):
        nuevas = 0
        for t in parse_transactions_full(pilot.web.get("/transactions", {"count": str(desde)}).html):
            if t.text in vistos:
                continue
            vistos.add(t.text)
            txs.append(t)
            nuevas += 1
        if nuevas == 0:
            break
    return pd.DataFrame(moves_table(txs, pilot.season(), INICIO_TEMPORADA))

mov = leer_movimientos()
if mov.empty:
    print("⚠ No pude leer movimientos. Pega en el chat de Cowork este texto para ajustar el lector:")
    print(BeautifulSoup(pilot.web.get("/transactions").html, "html.parser").get_text(" ")[:1500])
else:
    mov["equipo"] = mov["team_id"].map(nombre_eq).fillna("")
    mov.to_csv(os.path.join(carpeta_6c, "movimientos_liga.csv"), index=False)
    desconocidas = (mov["accion"] == "?").mean()
    sin_pos = (mov["pos"] == "").mean()
    print(f"Movimientos leídos: {len(mov)} (altas {int((mov['accion']=='alta').sum())}, "
          f"bajas {int((mov['accion']=='baja').sum())}, trades {int((mov['accion']=='trade').sum())}); "
          f"sin clasificar {desconocidas:.0%}, sin posición {sin_pos:.0%}")
    if desconocidas > 0.1 or sin_pos > 0.2:
        print("⚠ El lector no entendió bien algunas filas. Pega en el chat de Cowork estas 3 filas de ejemplo:")
        for t in parse_transactions_full(pilot.web.get("/transactions").html)[:3]:
            print("   ", t.text)
altas = mov[mov["accion"] == "alta"] if not mov.empty else pd.DataFrame(columns=["team_id", "semana", "pos", "puja"])

# ---------------- rosters de la semana W ----------------
ros_W = {}
for t in equipos:
    tid = str(t.team_id)
    try:
        r = pilot.load_roster(W, team_id=tid)
        pilot.enrich(r.players, W)
        ros_W[tid] = r
    except Exception as exc:  # noqa: BLE001
        print(f"⚠ No pude leer el roster de {t.name}: {str(exc)[:80]}")
if MI_ID not in ros_W:
    raise RuntimeError("No pude leer tu propio roster; corre otra vez las celdas 3 y 3b.")
SLOTS = [norm_slot(s) for s in ros_W[MI_ID].slots]
DED = {pos: SLOTS.count(pos) for pos in BASICAS}
NFLEX = sum(1 for s in SLOTS if s in ("W/R/T", "W/R", "W/T", "Q/W/R/T"))

def huecos(jugadores, semana_, usar_proy=True):
    """Posiciones donde no alcanzan los jugadores disponibles esa semana."""
    out = {}
    disp = defaultdict(list)
    for p in jugadores:
        if p.position not in BASICAS:
            continue
        en_bye = p.team in BYES.get(semana_, set())
        if en_bye or p.status in INACTIVOS or (usar_proy and (p.proj or 0) <= 0):
            continue
        disp[p.position].append(p)
    for pos in BASICAS:
        falta = DED[pos] - len(disp[pos])
        if falta > 0:
            out[pos] = falta
    sobra_flex = sum(max(0, len(disp[pos]) - DED[pos]) for pos in ("RB", "WR", "TE"))
    if sobra_flex < NFLEX and not any(k in out for k in ("RB", "WR", "TE")):
        out["FLEX (RB/WR/TE)"] = NFLEX - sobra_flex
    return out, disp

# fuerza de titulares por posición vs liga
fuerza = {}
for tid, r in ros_W.items():
    _, disp = huecos(r.players, W)
    fuerza[tid] = {pos: sum(sorted((p.proj or 0) for p in disp[pos])[::-1][:DED[pos]]) / max(1, DED[pos]) for pos in BASICAS}
liga_med = {pos: np.median([f[pos] for f in fuerza.values()]) for pos in BASICAS}

# ---------------- examen: ¿quién agrega y en qué posición? (modelo aprendido de la liga) ----------------
# La regla vieja ("si tiene un hueco por descanso, puja ahí") anticipaba muy pocas altas: la mayoría son
# pateadores y defensas que se rotan cada semana, managers que agregan algo cada semana, lesiones y
# posiciones que rinden poco. El modelo junta todo eso y se examina semana por semana (solo con el pasado).
from fantasy_autopilot import adds as _adds
ARCH_H = os.path.join(carpeta_6c, "historial_proyecciones.csv")
hh = pd.read_csv(ARCH_H, dtype={"team_id": str, "pid": str}) if os.path.exists(ARCH_H) else pd.DataFrame()
_hist_6c = pilot.history_rows(range(1, W))   # rosters de todos en cada semana (historial de la 7d o páginas de partido)
_ros_rows = [dict(team_id=r.team_id, week=r.week, pos=r.pos, team=r.team, slot=r.slot, proj=r.proj, pts=r.pts,
                  status=r.status) for r in _hist_6c if r.team_id]
_casos = _adds.build_cases(_ros_rows, altas.to_dict("records") if len(altas) else [], BYES, DED,
                           range(2, W + 1), label_through=W - 1)
ex_altas = _adds.exam(_casos)
prob_altas = _adds.predict(_casos, W)
ev = [c for c in _casos if c.added is not None]
vp = int(round(ex_altas.model_recall * ex_altas.adds)); fp = int(round(vp / max(ex_altas.model_precision, 1e-9))) - vp
_prec = ex_altas.model_precision
if ex_altas.cases:
    print(f"\nEXAMEN: ¿quién agrega y en qué posición? ({ex_altas.cases} casos equipo-semana-posición, "
          f"{ex_altas.adds} altas reales; cada semana predicha solo con las anteriores)")
    print(f"  Regla vieja (hueco por descanso): anticipó {ex_altas.rule_recall:.0%} de las altas; "
          f"cuando dijo 'va a agregar' acertó {ex_altas.rule_precision:.0%}.")
    print(f"  Modelo nuevo (marca tantos casos como altas espera, {ex_altas.expected:.0f}): anticipó "
          f"{ex_altas.model_recall:.0%} de las altas; cuando dijo 'va a agregar' acertó {ex_altas.model_precision:.0%}.")
    if ex_altas.auc_model is not None:
        print(f"  Ordenar de más a menos probable (AUC: 50% = azar, 100% = perfecto): modelo {ex_altas.auc_model:.0%}"
              + (f", regla vieja {ex_altas.auc_rule:.0%}" if ex_altas.auc_rule is not None else ""))
    print("  Por posición (anticipadas / reales): " + ", ".join(f"{p} {a}/{n}" for p, (a, n) in sorted(ex_altas.by_pos.items())))
    print("  Una alta depende de noticias que todavía no salen (lesiones del domingo, un suplente que explota):"
          " ningún modelo las ve venir; lo que sí se ve es QUIÉN agrega y en qué posiciones.")
else:
    print("\nSin semanas pasadas leídas: no se puede examinar la predicción de altas todavía.")
PRECISION_MIN, CASOS_MIN = 0.40, 10
EXAMEN_OK = ex_altas.cases > 0 and (vp + fp) >= CASOS_MIN and _prec >= PRECISION_MIN

# ---------------- perfiles y predicción ----------------
perfil, predicciones = [], []
for tid, r in ros_W.items():
    a = altas[altas["team_id"] == tid] if not altas.empty else altas
    semanas_jugadas = max(1, W - 1)
    pujas = a["puja"].dropna()
    ultimas = a[a["semana"] >= W - 3] if len(a) else a
    inactivo = len(ultimas) == 0
    hue, _ = huecos(r.players, W)
    debil = min(("QB", "RB", "WR", "TE"), key=lambda pos: fuerza[tid][pos] - liga_med[pos])
    probs_t = prob_altas.get(tid, {})
    top = sorted(probs_t.items(), key=lambda kv: -kv[1])[:2]
    perfil.append({
        "Rank": rank.get(tid, 99), "Equipo": f"{nombre_eq[tid]} ({manager_eq[tid]})",
        f"Huecos semana {W}": ", ".join(f"{k} x{v}" for k, v in hue.items()) or "ninguno",
        "Más débil": f"{debil} ({fuerza[tid][debil] - liga_med[debil]:+.1f})",
        "FAAB": faab_eq.get(tid), "Altas/semana": round(len(a) / semanas_jugadas, 1),
        "Puja típica": f"${pujas.median():.0f} (máx ${pujas.max():.0f})" if len(pujas) else "—",
        "Posiciones que más busca": ", ".join(f"{p} {n}" for p, n in Counter(a["pos"]).most_common(3)) if len(a) else "—",
        f"Prob. de agregar semana {W}": ", ".join(f"{p} {v:.0%}" for p, v in top) or "—",
        "Activo": "no (sin altas en 3 semanas)" if inactivo else "sí",
    })
    for pos, prob in probs_t.items():
        if prob >= 0.25:
            predicciones.append({"team_id": tid, "Equipo": nombre_eq[tid], "Rank": rank.get(tid, 99), "Posición": pos,
                                 "Prob. de pujar": prob, "Puja típica": pujas.median() if len(pujas) else 1})
print(f"\nPERFIL Y NECESIDADES DE CADA EQUIPO (semana {W})")
display(pd.DataFrame(perfil).sort_values("Rank"))
pr = pd.DataFrame(predicciones)
if len(pr):
    print(f"\nPREDICCIÓN: quién probablemente agrega esta semana y en qué posición (25% o más)")
    display(pr.sort_values("Prob. de pujar", ascending=False).assign(**{"Prob. de pujar": lambda d: d["Prob. de pujar"].map("{:.0%}".format)}).drop(columns="team_id"))

# ---------------- comportamiento de cada manager y amenazas a TUS pujas ----------------
perfiles = manager_profiles(mov.to_dict("records") if not mov.empty else [],
                            hh.to_dict("records") if not hh.empty else [], last_week_played=W - 1)
_ARCH_MH = os.path.join(carpeta_6c, "historia_movimientos.csv")
if os.path.exists(_ARCH_MH):  # pujas de temporadas pasadas (celda 6e): cuánto paga cada manager de verdad
    _mh = pd.read_csv(_ARCH_MH)
    _tid_de = {m: t for t, m in manager_eq.items() if m}
    _n = 0
    for _man, _g in _mh.groupby("manager"):
        _t = _tid_de.get(_man)
        if _t in perfiles:
            _b = [int(b) for b in pd.to_numeric(_g["puja"], errors="coerce").dropna()]
            perfiles[_t].bids += _b
            _n += len(_b)
    print(f"Sumé {_n} pujas de temporadas pasadas a los perfiles (celda 6e).")
filas_c = []
for tid, p in perfiles.items():
    filas_c.append({"Rank": rank.get(tid, 99), "Equipo": f"{nombre_eq.get(tid, tid)} ({manager_eq.get(tid, '')})",
                    "Altas": p.adds, "Puja típica": f"${p.typical_bid:.0f}", "Puja alta (75%)": f"${p.high_bid:.0f}",
                    "Máxima": f"${p.max_bid}", "Altas que no usó": f"{p.unused} de {p.adds_checked}",
                    "Tasa (frenada)": f"{p.unused_rate:.0%}", "FAAB": faab_eq.get(tid),
                    "Ejemplos sin usar": ", ".join(p.unused_names[-3:])})
if filas_c:
    print("\nCÓMO JUEGA CADA MANAGER (altas que no usó = nunca titular en las 2 semanas siguientes:"
          " bloqueo o reserva; desde afuera se ven igual)")
    display(pd.DataFrame(filas_c).sort_values("Rank"))
huecos_W = {tid: [k if k in BASICAS else "RB" for k in huecos(r.players, W)[0]] for tid, r in ros_W.items()}
mis_pujas = []
_rw = globals().get("r_waivers")
if _rw is not None and getattr(_rw, "data", None):
    mis_pujas = [(c.add.name, c.add.position, int(c.bid)) for c in _rw.data.get("claims", []) if c.on_waivers]
amenazas = claim_threats(mis_pujas, perfiles, faab_eq, huecos_W, MI_ID, W)
print("\nAMENAZAS A TUS PUJAS DE ESTA SEMANA (de la celda 6)")
if not mis_pujas:
    print("La celda 6 no sugirió pujas por waivers (o no la corriste antes). Corre 6 y luego 6c.")
elif not amenazas:
    print("Nadie activo suele pagar lo que tú vas a pujar ni necesita esas posiciones: tus pujas están bien.")
else:
    display(pd.DataFrame([{"Tu objetivo": f"{a.target} ({a.pos})", "Tu puja": f"${a.my_bid}",
                           "Quién te lo puede quitar": nombre_eq.get(a.team_id, a.team_id),
                           "Por qué": a.reason, "Su puja probable": f"${a.their_bid}",
                           "Para ganarle": f"${a.beat_with}"} for a in amenazas]))
    print("Regla: sube tu puja a 'Para ganarle' solo si el jugador de verdad mejora tu alineación. "
          "Si no, deja tu puja y acepta perderlo: pagar de más por bloquear no da puntos.")

# ---------------- mapa de trades: quién tiene de sobra lo que te falta, y qué le falta a él ----------------
from fantasy_autopilot.optimizer import assign as _assign
def _mejor(jug):
    activos = [p for p in jug if p.slot != "IR"]
    elegidos = _assign(activos, SLOTS, lambda p, s: (p.expected if hasattr(p, "expected") else p.proj) + 1e-9)
    return {id(p) for p in elegidos if p is not None}, [(s, p) for s, p in zip(SLOTS, elegidos)]
_mis_jug = ros_W[MI_ID].players
_mis_tit, _mi_alin = _mejor(_mis_jug)
_flex_mio = [p for s, p in _mi_alin if p is not None and s in ("W/R/T", "W/R", "W/T", "Q/W/R/T")]
_umbral = min((p.expected for p in _flex_mio), default=0.0)
_mi_banca = [p for p in _mis_jug if p.slot != "IR" and id(p) not in _mis_tit and p.position in BASICAS]
mapa = []
for tid, r in ros_W.items():
    if tid == MI_ID:
        continue
    sus_tit, su_alin = _mejor(r.players)
    sobra = sorted((p for p in r.players if p.slot != "IR" and id(p) not in sus_tit
                    and p.position in ("RB", "WR", "TE") and p.expected > _umbral + 1.0), key=lambda p: -p.expected)
    if not sobra:
        continue
    debil = min(("QB", "RB", "WR", "TE"), key=lambda pos: fuerza[tid][pos] - liga_med[pos])
    su_peor = min((p.expected for s, p in su_alin if p is not None and p.position == debil), default=0.0)
    le_sirve = [p for p in _mi_banca if p.position == debil and p.expected > su_peor]
    mapa.append({"Equipo": f"{nombre_eq[tid]} ({manager_eq.get(tid, '')})", "Rank": rank.get(tid, 99),
                 f"Banca suya que entra a tu FLEX (> {_umbral:.2f})": ", ".join(f"{p.name} {p.expected:.2f}" for p in sobra[:3]),
                 "Su posición más débil": debil,
                 "Tu banca que él pondría de titular": ", ".join(f"{p.name} {p.expected:.2f}" for p in le_sirve[:3]) or "nada claro"})
print(f"\nMAPA DE TRADES (semana {W}): quién tiene en la banca algo mejor que tu FLEX y qué le falta a él")
if mapa:
    display(pd.DataFrame(mapa).sort_values("Rank"))
    print("Esto solo dice con quién hablar. Antes de ofrecer, corre la 7c: calcula el trade completo para los dos "
          "lados en lo que queda de temporada (descansos incluidos). Si 'Tu banca que él pondría' dice 'nada claro', "
          "es difícil que acepte sin que le des un titular.")
else:
    print("Nadie tiene en la banca un corredor, receptor o ala cerrada claramente mejor que tu FLEX.")

# ---------------- bloqueos ----------------
try:
    rival = next((b.team_id if a.team_id == MI_ID else a.team_id) for a, b in pilot.web.matchups(W)
                 if MI_ID in (a.team_id, b.team_id))
except Exception:  # noqa: BLE001
    rival = None
libres_cache = {}
def mejores_libres(pos, n=8):
    if pos in libres_cache:
        return libres_cache[pos]
    out = []
    for row in pilot.web.players(pos, status="A")[:n]:
        try:
            nota = pilot.web.playernote(row.pid)
        except Exception:  # noqa: BLE001
            continue
        if nota.owner_team_id:
            continue
        semanal = projected_weekly(nota, W)
        if row.status in INACTIVOS:
            continue
        out.append((row.name, semanal.get(W, 0.0), row.availability or "?"))
    libres_cache[pos] = sorted(out, key=lambda x: x[1], reverse=True)
    return libres_cache[pos]

mios = ros_W[MI_ID].players
if not EXAMEN_OK:
    pr = pd.DataFrame()  # sin bloqueos automáticos
    print(f"\nBLOQUEOS: no se recomiendan. La predicción de altas acertó {_prec:.0%} en {vp + fp} "
          f"casos (hace falta {PRECISION_MIN:.0%} con al menos {CASOS_MIN}). Gastar FAAB en bloqueos con esa "
          "puntería sería adivinar.")
banca_mia = sorted((p for p in mios if p.slot == "BN"), key=lambda p: p.proj or 0)
bloqueos = []
for _, f in (pr.iterrows() if len(pr) else []):
    tid = f["team_id"]
    if (tid == MI_ID or f["Posición"] in ("K", "DEF") or not (rank.get(tid, 99) < mi_rank or tid == rival)
            or f["Prob. de pujar"] < 0.4):
        continue
    libres = mejores_libres(f["Posición"])
    if len(libres) < 2:
        continue
    (n1, p1, disp1), (n2, p2, _) = libres[0], libres[1]
    gap = p1 - p2
    if gap < GAP_MINIMO:
        continue
    puja = int(max(1, (f["Puja típica"] or 0) + 1))
    puja += 1 - puja % 2  # impar
    soltar = banca_mia[0].name if banca_mia else "?"
    me_sirve = any(p.position == f["Posición"] and (p.proj or 0) < p1 for p in mios if p.slot not in ("BN", "IR"))
    bloqueos.append({"Quitarle a": f"{f['Equipo']} (rank {rank.get(tid, '?')}{', TU RIVAL' if tid == rival else ''})",
                     "Jugador libre": f"{n1} ({f['Posición']}, {disp1})", f"Proy. semana {W}": round(p1, 2),
                     "Siguiente mejor libre": f"{n2} {p2:.2f}", "Ventaja": round(gap, 2),
                     "Prob. de que él puje": f"{f['Prob. de pujar']:.0%}", "Tu puja sugerida": f"${puja}",
                     "Soltar": soltar, "¿Te sirve a ti?": "sí" if me_sirve else "solo bloqueo"})
if EXAMEN_OK:
    print("\nBLOQUEOS SUGERIDOS (equipos arriba de ti o tu próximo rival)")
if not EXAMEN_OK:
    pass
elif bloqueos:
    display(pd.DataFrame(bloqueos))
    print("Regla: bloquea solo si el jugador te sirve a ti también o si es tu rival de esa semana; "
          "si es 'solo bloqueo' y la puja pasa de $3, no vale la pena.")
else:
    print("Ninguno vale la pena: no hay un libre que sea claramente mejor que el siguiente en las posiciones que ellos necesitan.")

Movimientos leídos: 252 (altas 125, bajas 117, trades 10); sin clasificar 0%, sin posición 0%

EXAMEN: ¿quién agrega y en qué posición? (360 casos equipo-semana-posición, 73 altas reales; cada semana predicha solo con las anteriores)
  Regla vieja (hueco por descanso): anticipó 12% de las altas; cuando dijo 'va a agregar' acertó 43%.
  Modelo nuevo (marca tantos casos como altas espera, 76): anticipó 42% de las altas; cuando dijo 'va a agregar' acertó 41%.
  Ordenar de más a menos probable (AUC: 50% = azar, 100% = perfecto): modelo 78%, regla vieja 54%
  Por posición (anticipadas / reales): DEF 16/20, K 2/11, QB 2/9, RB 6/12, TE 1/6, WR 4/15
  Una alta depende de noticias que todavía no salen (lesiones del domingo, un suplente que explota): ningún modelo las ve venir; lo que sí se ve es QUIÉN agrega y en qué posiciones.

PERFIL Y NECESIDADES DE CADA EQUIPO (semana 8)

,Rank,Equipo,Huecos semana 8,Más débil,FAAB,Altas/semana,Puja típica,Posiciones que más busca,Prob. de agregar semana 8,Activo
1,1,At least I'm not Dallas (JOSHUA),ninguno,WR (-1.7),26,3.6,$7 (máx $12),"WR 6, TE 5, DEF 5","DEF 68%, TE 46%",sí
3,2,End Zone Hunters (Douglas),ninguno,RB (-2.0),100,0.0,—,—,"DEF 10%, RB 8%",no (sin altas en 3 semanas)
11,3,T-Law & Fornication (Preston),ninguno,QB (-3.7),85,2.9,$0 (máx $4),"WR 8, RB 4, QB 4","DEF 47%, QB 42%",sí
10,4,Silly Old Sawyer (mike),K x1,QB (-2.5),100,0.6,—,"DEF 3, QB 1","DEF 35%, K 28%",sí
5,5,Fourth Quarter Delio (Delio),ninguno,QB (-1.9),74,2.9,$2 (máx $6),"DEF 5, WR 5, K 4","DEF 41%, WR 38%",sí
2,6,Better Luck NextYear (Ron),ninguno,RB (-4.3),100,0.0,—,—,"QB 19%, DEF 11%",no (sin altas en 3 semanas)
9,7,Riddle Renegades (Keith),ninguno,TE (-1.3),100,0.7,—,"WR 2, DEF 2, K 1","DEF 27%, WR 17%",sí
6,8,Guap Goblin (Brian),ninguno,QB (-4.5),100,0.3,—,"QB 1, WR 1","DEF 18%, WR 11%",sí
0,9,0-17 (Gregg),ninguno,WR (-2.1),100,1.1,$0 (máx $0),"DEF 3, RB 2, WR 1","DEF 50%, QB 43%",sí
4,10,Fahim n Furious (Fahim),K x1,WR (-1.1),100,0.0,—,—,"K 20%, DEF 13%",no (sin altas en 3 semanas)
8,11,Mountain Top (Tito),ninguno,WR (-1.4),99,1.0,$0 (máx $1),"WR 3, K 2, DEF 1","TE 37%, DEF 28%",sí
7,12,Mountain Drew (Drew Commissioner),ninguno,RB (-4.1),9,4.9,$5 (máx $19),"RB 12, WR 11, DEF 6","DEF 68%, RB 53%",sí

PREDICCIÓN: quién probablemente agrega esta semana y en qué posición (25% o más)

                     Equipo  Rank Posición Prob. de pujar  Puja típica
9   At least I'm not Dallas     1      DEF            68%          7.0
19            Mountain Drew    12      DEF            68%          5.0
15            Mountain Drew    12       RB            53%          5.0
3                      0-17     9      DEF            50%          0.0
30      T-Law & Fornication     3      DEF            47%          0.0
7   At least I'm not Dallas     1       TE            46%          7.0
0                      0-17     9       QB            43%          0.0
25      T-Law & Fornication     3       QB            42%          0.0
13     Fourth Quarter Delio     5      DEF            41%          1.5
27      T-Law & Fornication     3       WR            41%          0.0
16            Mountain Drew    12       WR            41%          5.0
4   At least I'm not Dallas     1       QB            40%          7.0
6   At least I'm not Dallas     1       WR            40%          7.0
18            Mountain Drew    12        K            39%          5.0
11     Fourth Quarter Delio     5       WR            38%          1.5
20             Mountain Top    11       TE            37%          0.0
26      T-Law & Fornication     3       RB            37%          0.0
24         Silly Old Sawyer     4      DEF            35%          1.0
8   At least I'm not Dallas     1        K            34%          7.0
2                      0-17     9       WR            32%          0.0
12     Fourth Quarter Delio     5        K            32%          1.5
5   At least I'm not Dallas     1       RB            31%          7.0
17            Mountain Drew    12       TE            28%          5.0
21             Mountain Top    11      DEF            28%          0.0
23         Silly Old Sawyer     4        K            28%          1.0
14            Mountain Drew    12       QB            28%          5.0
22         Riddle Renegades     7      DEF            27%          1.0
10     Fourth Quarter Delio     5       QB            26%          1.5
29      T-Law & Fornication     3        K            26%          0.0
28      T-Law & Fornication     3       TE            26%          0.0
1                      0-17     9       RB            25%          0.0

CÓMO JUEGA CADA MANAGER (altas que no usó = nunca titular en las 2 semanas siguientes: bloqueo o reserva; desde afuera se ven igual)

,Rank,Equipo,Altas,Puja típica,Puja alta (75%),Máxima,Altas que no usó,Tasa (frenada),FAAB,Ejemplos sin usar
3,1,At least I'm not Dallas (JOSHUA),25,$12,$12,$12,7 de 13,55%,26,"Ollie Gordon II (sem 4, $7), T.J. Hockenson (s..."
4,3,T-Law & Fornication (Preston),20,$4,$4,$4,11 de 13,80%,85,"Drew Lock (sem 3), Caleb Douglas (sem 2), Jaco..."
8,4,Silly Old Sawyer (mike),4,$0,$0,$0,0 de 1,44%,100,
0,5,Fourth Quarter Delio (Delio),20,$5,$6,$6,4 de 5,72%,74,"Daniel Jones (sem 4), Michael Pittman Jr. (sem..."
5,7,Riddle Renegades (Keith),5,$0,$0,$0,1 de 2,56%,100,Wan'Dale Robinson (sem 6)
7,8,Guap Goblin (Brian),2,$0,$0,$0,1 de 2,56%,100,Cooper Kupp (sem 0)
6,9,0-17 (Gregg),8,$0,$0,$0,0 de 3,30%,100,
2,11,Mountain Top (Tito),7,$1,$1,$1,0 de 3,30%,99,
1,12,Mountain Drew (Drew Commissioner),34,$7,$11,$19,11 de 17,64%,9,"Kaelon Black (sem 2, $1), Emari Demercado (sem..."

AMENAZAS A TUS PUJAS DE ESTA SEMANA (de la celda 6)
La celda 6 no sugirió pujas por waivers (o no la corriste antes). Corre 6 y luego 6c.

MAPA DE TRADES (semana 8): quién tiene en la banca algo mejor que tu FLEX y qué le falta a él
Nadie tiene en la banca un corredor, receptor o ala cerrada claramente mejor que tu FLEX.

In [ ]:
#@title 6d. Lesionados libres que vale la pena guardar { display-mode: "form" }
#@markdown Busca jugadores **libres** que están lesionados (O, IR, PUP) pero que Yahoo todavía proyecta bien
#@markdown cuando vuelvan, sobre todo para los playoffs (semanas 15 a 17). Nadie los toma porque hoy no juegan.
#@markdown Guía de regreso (estudios médicos de la NFL): tobillo alto 2 a 6 semanas; isquiotibial 1 a 4 semanas
#@markdown con 16-31% de recaída; ligamento cruzado (ACL) o tendón de Aquiles: temporada terminada.
#@markdown Cuándo vale la pena: si tienes el IR libre, casi siempre; si cuesta un lugar de banca, solo si
#@markdown vuelve antes de la semana 13 y le ganaría a tus titulares en los playoffs.
POR_POSICION = 15  #@param {type:"integer"}
import numpy as np
import pandas as pd
from fantasy_autopilot.engine import projected_weekly

LESION = {"acl": "temporada terminada (ACL)", "achilles": "temporada terminada (Aquiles)",
          "high ankle": "2 a 6 semanas (tobillo alto)", "ankle": "1 a 4 semanas (tobillo)",
          "hamstring": "1 a 4 semanas, riesgo de recaída", "concussion": "1 a 2 semanas (conmoción)",
          "knee": "depende: revisa noticias (rodilla)", "foot": "depende: revisa noticias (pie)"}
FUERA = {"O", "IR", "PUP", "NFI", "D", "NA"}
S6 = pilot.week()
PLAYOFF = [15, 16, 17]
filas = []
for pos in ("QB", "RB", "WR", "TE"):
    for row in pilot.web.players(pos, status="A")[:POR_POSICION]:
        if row.status not in FUERA:
            continue
        try:
            nota = pilot.web.playernote(row.pid)
        except Exception:  # noqa: BLE001
            continue
        if nota.owner_team_id:
            continue
        semanal = projected_weekly(nota, S6)
        info = pilot.sleeper.match(yahoo_id=str(row.pid), name=row.name) if pilot.sleeper else None
        parte = (info or {}).get("injury_body_part") or ""
        guia = next((v for k, v in LESION.items() if k in parte.lower()), "revisa noticias")
        filas.append({
            "Jugador": row.name, "Pos": pos, "Equipo": row.team, "Estado": row.status,
            "Lesión": parte or "?", "Regreso típico": guia,
            "Semanas con proyección": sum(1 for w, v in semanal.items() if v > 0),
            "Proy. si vuelve en 4 semanas": round(sum(v for w, v in semanal.items() if w >= S6 + 4), 1),
            "Proy. playoffs (15-17)": round(sum(semanal.get(w, 0.0) for w in PLAYOFF), 1),
            "Disponible": row.availability,
        })
tabla_6d = pd.DataFrame(filas)
if tabla_6d.empty:
    print("No encontré lesionados libres con proyección entre los primeros de cada posición.")
else:
    tabla_6d = tabla_6d[~tabla_6d["Regreso típico"].str.startswith("temporada")].sort_values(
        "Proy. playoffs (15-17)", ascending=False)
    display(tabla_6d)
    print("Antes de guardar a uno: busca la noticia de su regreso (semanas que faltan) y compáralo con tu "
          "peor jugador de banca. Si tu IR está libre, pon ahí al mejor de esta lista.")

In [ ]:
#@title 6e. Historia de la liga: temporadas pasadas (quién ganó y cómo) { display-mode: "form" }
#@markdown Córrela **una vez** (tarda unos minutos; guarda todo en tu carpeta de Drive y no hace falta repetirla).
#@markdown Busca las temporadas pasadas de esta liga en Yahoo y lee de cada una: clasificación final, puntos,
#@markdown managers, todos los movimientos (altas, bajas, pujas, trades). Luego muestra:
#@markdown 1. Quién ganó cada año y qué hizo distinto (altas, dinero gastado, trades, puntos a favor).
#@markdown 2. Cómo juega cada manager actual a lo largo de los años (sus pujas pasadas mejoran la celda 6c).
#@markdown Si no encuentra las temporadas solas, abre en Yahoo la temporada pasada de tu liga, copia la
#@markdown dirección del navegador (se parece a `.../2025/f1/123456`) y pégala aquí abajo (varias, con comas).
TEMPORADAS_MANUALES = ""  #@param {type:"string"}
import io, os, re, time
from datetime import date, timedelta
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from fantasy_autopilot.yahoo import parse as _yp
from fantasy_autopilot.league import moves_table

carpeta_6e = getattr(pilot.cfg, "state_dir", None) or "/content"
BASE = pilot.web.base_url

def _get_abs(url):
    time.sleep(4.0)
    resp = pilot.web.session.get(url, timeout=40)
    if _yp.is_login_page(resp.url, resp.text):
        raise RuntimeError("Yahoo pidió iniciar sesión: actualiza las cookies (celda 3).")
    if resp.status_code >= 400:
        raise RuntimeError(f"HTTP {resp.status_code} en {url}")
    return resp.text

# ---------------- 1. encontrar temporadas pasadas ----------------
encontradas = {}
def _buscar_links(html):
    for m in re.finditer(r"/(20\d\d)/f1/(\d+)", html or ""):
        anio, lid = int(m.group(1)), m.group(2)
        if anio < pilot.season():
            encontradas[anio] = lid
for ruta in ("/history", "", "/settings"):
    try:
        _buscar_links(pilot.web.get(ruta).html)
    except Exception as exc:  # noqa: BLE001
        print(f"(no pude leer {ruta or 'la portada'}: {str(exc)[:60]})")
for url in [u.strip() for u in TEMPORADAS_MANUALES.split(",") if u.strip()]:
    _buscar_links(url)
# cada temporada vieja enlaza a la anterior: seguir la cadena
for _ in range(15):
    nuevos = 0
    for anio, lid in sorted(encontradas.items()):
        if any(a < anio for a in encontradas):
            continue
        try:
            antes = len(encontradas)
            _buscar_links(_get_abs(f"{BASE}/{anio}/f1/{lid}/history"))
            nuevos += len(encontradas) - antes
        except Exception:  # noqa: BLE001
            pass
    if not nuevos:
        break
if not encontradas:
    print("No encontré temporadas pasadas. Puede que esta liga empezó en", pilot.season(),
          "o que Yahoo no muestra el enlace. Si existe una temporada pasada, pega su dirección en "
          "TEMPORADAS_MANUALES y vuelve a correr.")
else:
    print("Temporadas encontradas:", ", ".join(f"{a} (liga {l})" for a, l in sorted(encontradas.items())))

# ---------------- 2. leer cada temporada ----------------
def _clasificacion(html, anio):
    filas = []
    for tabla in pd.read_html(io.StringIO(html)):
        cols = [str(c) for c in tabla.columns]
        if not any("W-L" in c for c in cols):
            continue
        c_eq = next((c for c in tabla.columns if "Team" in str(c)), tabla.columns[1])
        c_wl = next(c for c in tabla.columns if "W-L" in str(c))
        c_pf = next((c for c in tabla.columns if str(c).strip() in ("PF", "Pts For", "Points For")), None)
        for i, f in tabla.iterrows():
            filas.append({"anio": anio, "rank": int(re.sub(r"\D", "", str(f[tabla.columns[0]])) or i + 1),
                          "equipo": str(f[c_eq]), "w_l_t": str(f[c_wl]),
                          "pf": pd.to_numeric(str(f[c_pf]).replace(",", ""), errors="coerce") if c_pf is not None else np.nan})
        break
    return filas

temporadas, movs_hist = [], []
for anio, lid in sorted(encontradas.items()):
    base = f"{BASE}/{anio}/f1/{lid}"
    try:
        tabla = []
        for sufijo in ("/standings", ""):
            tabla = _clasificacion(_get_abs(base + sufijo), anio)
            if tabla:
                break
        managers = {t.name: t.manager for t in _yp.parse_teams_page(_get_abs(base + "/teams"), lid)}
        for f in tabla:
            f["manager"] = next((m for n, m in managers.items() if n and n in f["equipo"]), "")
        temporadas += tabla
        txs, vistos = [], set()
        for desde in range(0, 2000, 25):
            nuevas = [t for t in _yp.parse_transactions_full(_get_abs(f"{base}/transactions?count={desde}"))
                      if t.text not in vistos]
            if not nuevas:
                break
            for t in nuevas:
                vistos.add(t.text)
            txs += nuevas
        # el martes antes del primer jueves de septiembre (aprox. inicio de temporada)
        d = date(anio, 9, 1)
        while d.weekday() != 3:
            d += timedelta(days=1)
        filas_m = moves_table(txs, anio, d - timedelta(days=2))
        nombre_tid = {t.team_id: (t.name, t.manager) for t in _yp.parse_teams_page(_get_abs(base + "/teams"), lid)}
        for m in filas_m:
            m["anio"] = anio
            m["equipo"], m["manager"] = nombre_tid.get(m["team_id"], ("", ""))
        movs_hist += filas_m
        print(f"  {anio}: {len(tabla)} equipos, {len(txs)} movimientos")
    except Exception as exc:  # noqa: BLE001
        print(f"  {anio}: no pude leerla ({str(exc)[:80]})")

tem = pd.DataFrame(temporadas)
mh = pd.DataFrame(movs_hist)
if len(tem):
    tem.to_csv(os.path.join(carpeta_6e, "historia_temporadas.csv"), index=False)
if len(mh):
    mh.to_csv(os.path.join(carpeta_6e, "historia_movimientos.csv"), index=False)

# ---------------- 3. qué hicieron los que ganaron ----------------
if len(tem) and len(mh):
    act = mh.groupby(["anio", "team_id"]).agg(
        altas=("accion", lambda s: int((s == "alta").sum())),
        gastado=("puja", lambda s: float(pd.to_numeric(s, errors="coerce").fillna(0).sum())),
        trades=("tipo", lambda s: int((s == "trade").sum()))).reset_index()
    eq_tid = mh.drop_duplicates(["anio", "team_id"])[["anio", "team_id", "equipo"]]
    act = act.merge(eq_tid, on=["anio", "team_id"])
    tabla = tem.merge(act, on=["anio", "equipo"], how="left")
    tabla[["altas", "gastado", "trades"]] = tabla[["altas", "gastado", "trades"]].fillna(0)
    print("\nCAMPEONES Y CÓMO JUGARON")
    display(tabla[tabla["rank"] == 1][["anio", "equipo", "manager", "w_l_t", "pf", "altas", "gastado", "trades"]])
    print("\nQUÉ SE RELACIONA CON TERMINAR ARRIBA (todas las temporadas; -1 = muy relacionado con buen puesto)")
    for col, nombre in (("pf", "puntos a favor"), ("altas", "número de altas"), ("gastado", "FAAB gastado"),
                        ("trades", "trades")):
        ok = tabla[["rank", col]].dropna()
        if len(ok) >= 8 and ok[col].std() > 0:
            r = np.corrcoef(ok["rank"], ok[col])[0, 1]
            print(f"  {nombre}: {r:+.2f}")
    print("  (con pocas temporadas estas relaciones son débiles: tómalas como pistas, no como reglas)")
    print("\nCADA MANAGER ACTUAL EN AÑOS PASADOS")
    actuales = {t.manager for t in pilot.web.teams()}
    pm = tabla[tabla["manager"].isin(actuales)].groupby("manager").agg(
        temporadas=("anio", "nunique"), mejor_puesto=("rank", "min"), puesto_medio=("rank", "mean"),
        altas_por_anio=("altas", "mean"), gastado_por_anio=("gastado", "mean"), trades_por_anio=("trades", "mean"))
    display(pm.round(1).sort_values("puesto_medio"))
    pujas = pd.to_numeric(mh["puja"], errors="coerce")
    print("Pujas ganadoras de años pasados (las usa la celda 6c para saber cuánto paga cada manager): "
          f"{int(pujas.notna().sum())} pujas, mediana ${pujas.median():.0f}, 90% ≤ ${pujas.quantile(0.9):.0f}")

In [21]:
# ===== CELDA 7c (versión 4): TRADES QUE LE CONVIENEN A LOS DOS =====
# Versión 4 (18 oct): tu lado también se mide como el evaluador de Yahoo (un hueco vale 0).
# Así no vuelve a sugerir trades que Yahoo te muestra en rojo, como dar a tu mariscal suplente.
# Versión 3 (18 oct): no ofrece a tus mejores jugadores, máximo 1 titular por trade,
# incluye a todos los managers (también Mike) y la tabla B sale para todos los equipos.
# Reemplaza el contenido de tu celda 7c con esta y córrela.
# Si no reiniciaste la sesión, reutiliza los rosters que ya leyó: no vuelve a visitar Yahoo
# (solo 2 páginas: semana y equipos). Para leer todo de nuevo, pon REFRESCAR = True.
#
# Qué hace:
#   1. Cuenta realista para ti: lesionados en 0 y los huecos (descanso o lesión) los llena
#      un agente libre. Todas las semanas valen igual.
#   2. Para el otro, la misma cuenta que le mostrará el evaluador de trades de Yahoo
#      (sin agentes libres: un hueco vale 0).
#   3. Prueba trades 1 por 1, 2 por 1, 1 por 2 y 2 por 2.
#   4. Nunca ofrece jugadores con O, D o IR, ni pateadores ni defensas.
#   5. Tabla A: trades que pasan todos los filtros (hasta 3 por equipo).
#   6. Tabla B: para los managers de FOCO, los 5 trades que más se acercan aunque no pasen,
#      con todos los números, para que tú decidas.
#   7. Tabla C: mapa de necesidades: en qué posición es débil cada equipo y qué le sobra.

import heapq
import itertools
from collections import Counter

import numpy as np
import pandas as pd
from fantasy_autopilot.nfl import norm_slot

# ---------------- ajustes ----------------
EXCLUIR_MANAGERS = []               # managers que no se evalúan (vacío = todos)
FOCO = []                           # vacío = tabla B para todos los equipos
PROTEGER_MEJORES = 5                # tus 5 mejores titulares (puntos restantes) nunca se ofrecen
MAX_TITULARES_DOY = 1               # máximo 1 de tus titulares por trade
MIN_TU_SEMANA = 0.5        # tu alineación debe subir al menos 0.5 pts por semana (cuenta realista)
MIN_TU_YAHOO = 5.0         # y el evaluador de Yahoo te debe mostrar al menos +5 en la temporada
MIN_ELLOS_YAHOO = 5.0      # lo que Yahoo le mostrará al otro, total de la temporada
MIN_ELLOS_REAL = 0.0       # y en la cuenta realista él tampoco pierde
MIN_JUSTO = 0.90           # él recibe al menos 90% de los puntos restantes que da
TAMANOS = [(1, 1), (2, 1), (1, 2), (2, 2)]   # (doy, recibo)
NO_OFRECER = {"O", "D", "IR", "PUP", "NFI", "SUSP", "NA"}
NO_PEDIR = {"O", "D", "IR", "PUP", "NFI", "SUSP", "NA"}   # no recibir lesionados
NO_CAMBIAR_POS = {"K", "DEF"}
POR_EQUIPO = 3
CERCANOS = 3
REFRESCAR = False
# Puntos por semana del 3.er mejor agente libre de cada posición
# (columna "Promedio resto" de tu celda 6, 1 oct). Cámbialos si la lista cambia.
REEMPLAZO = {"QB": 15.5, "RB": 5.7, "WR": 5.8, "TE": 5.7, "K": 8.5, "DEF": 5.6}
ULTIMA_SEMANA = 17
FLEX_POS = {"W/R/T": ("RB", "WR", "TE"), "W/R": ("RB", "WR"), "W/T": ("WR", "TE"),
            "Q/W/R/T": ("QB", "RB", "WR", "TE")}
BASICAS = ("QB", "RB", "WR", "TE", "K", "DEF")

# ---------------- leer rosters (una sola vez por sesión) ----------------
S = pilot.week()
equipos = pilot.web.teams()
MI_ID = str(pilot.cfg.team_id)
if REFRESCAR or "_ROSTERS_7C" not in globals():
    _ROSTERS_7C = {}

def cargar(team_id):
    """Roster por (equipo, semana), válido 30 minutos: nunca se usa uno de otra semana o de horas atrás."""
    import time as _t
    team_id = str(team_id)
    clave = (team_id, S)
    if clave not in _ROSTERS_7C or _t.time() - _ROSTERS_7C[clave][2] > 1800:
        ros = pilot.load_roster(S, team_id=team_id)
        pilot.enrich(ros.players, S)          # descuenta dudosos/fuera de esta semana también en rivales
        inicio = pilot._weekly_for_roster(ros.players, S)
        _ROSTERS_7C[clave] = (ros, inicio, _t.time())
        print(f"  leído {ros.team_name or team_id}: {len(ros.players)} jugadores")
    return _ROSTERS_7C[clave][:2]

mi_ros, inicio = cargar(MI_ID)
SEMANAS = list(range(inicio, ULTIMA_SEMANA + 1))
NS = len(SEMANAS)
SLOTS = [norm_slot(s) for s in mi_ros.slots]
DEDIC = Counter(s for s in SLOTS if s in BASICAS)
FLEX = [s for s in SLOTS if s not in BASICAS]
if len({FLEX_POS.get(f) for f in FLEX}) > 1 or any(f not in FLEX_POS for f in FLEX):
    raise RuntimeError(f"Esta celda solo sabe calcular un tipo de FLEX; tu liga tiene {FLEX}")
FPOS = FLEX_POS[FLEX[0]] if FLEX else ()

rivales = []
for t in equipos:
    if str(t.team_id) == MI_ID:
        continue
    if any(x.lower() in (t.manager or "").lower() for x in EXCLUIR_MANAGERS):
        print(f"Se excluye {t.name} ({t.manager})")
        continue
    ros, _ = cargar(t.team_id)
    rivales.append((t, ros))

# ---------------- matemática de alineación ----------------
V = {}
def v(p):
    if p.pid not in V:
        V[p.pid] = np.array([p.weekly.get(w, 0.0) for w in SEMANAS], dtype=float)
    return V[p.pid]

REPL = {pos: np.full(NS, REEMPLAZO.get(pos, 0.0)) for pos in BASICAS}

def alineacion(jugadores, con_reemplazo, por_pos=False):
    """Puntos de la mejor alineación, semana por semana. Con por_pos=True devuelve
    también los puntos de los titulares fijos de cada posición."""
    total = np.zeros(NS)
    sobrantes, detalle = [], {}
    for pos in BASICAS:
        n = DEDIC.get(pos, 0)
        filas = [v(p) for p in jugadores if p.position == pos]
        if con_reemplazo:
            filas += [REPL[pos]] * max(1, n)
        if not filas:
            detalle[pos] = np.zeros(NS)
            continue
        M = -np.sort(-np.vstack(filas), axis=0)
        k = min(n, len(M))
        total += M[:k].sum(axis=0)
        detalle[pos] = M[:k].sum(axis=0)
        if pos in FPOS and len(M) > k:
            sobrantes.append(M[k:])
    if FLEX and sobrantes:
        M = -np.sort(-np.vstack(sobrantes), axis=0)
        total += M[:len(FLEX)].sum(axis=0)
    return (total, detalle) if por_pos else total

def resto(p):
    return float(v(p).sum())

def nombres(ps):
    return " + ".join(p.name for p in ps)

def etiqueta(t):
    return f"{t.name} ({t.manager})"

# ---------------- tabla C: mapa de necesidades ----------------
todos = [(None, mi_ros)] + rivales
por_equipo_pos = {}
for t, ros in todos:
    js = [p for p in ros.players if p.position in BASICAS]
    _, det = alineacion(js, False, por_pos=True)
    por_equipo_pos[t.team_id if t else MI_ID] = {pos: det[pos].sum() / NS / max(1, DEDIC[pos]) for pos in BASICAS}
liga = {pos: np.mean([d[pos] for d in por_equipo_pos.values()]) for pos in BASICAS}

def mapa(t, ros):
    d = por_equipo_pos[t.team_id if t else MI_ID]
    dif = {pos: d[pos] - liga[pos] for pos in ("QB", "RB", "WR", "TE")}
    debil = min(dif, key=dif.get)
    fuerte = max(dif, key=dif.get)
    js = [p for p in ros.players if p.position in ("QB", "RB", "WR", "TE")]
    titulares = set()
    for pos in ("QB", "RB", "WR", "TE"):
        orden = sorted((p for p in js if p.position == pos), key=resto, reverse=True)
        titulares |= {p.pid for p in orden[:DEDIC.get(pos, 0)]}
    flex = sorted((p for p in js if p.position in FPOS and p.pid not in titulares), key=resto, reverse=True)
    titulares |= {p.pid for p in flex[:len(FLEX)]}
    banca = sorted((p for p in js if p.pid not in titulares and p.status not in NO_OFRECER),
                   key=resto, reverse=True)
    sobra = ", ".join(f"{p.name} ({p.position} {resto(p) / NS:.1f})" for p in banca[:2]) or "nada"
    return {
        "Equipo": etiqueta(t) if t else "TÚ",
        "Más débil en": f"{debil} ({dif[debil]:+.1f} pts/sem vs liga)",
        "Más fuerte en": f"{fuerte} ({dif[fuerte]:+.1f})",
        "Le sobra en la banca": sobra,
    }

tabla_c = pd.DataFrame([mapa(t, ros) for t, ros in todos])

# ---------------- búsqueda ----------------
mios = [p for p in mi_ros.players if p.position in BASICAS]
base_mio = alineacion(mios, True)
base_mio_yahoo = alineacion(mios, False)
campo = [p for p in mios if p.position not in NO_CAMBIAR_POS]
mis_titulares = set()
for pos in ("QB", "RB", "WR", "TE"):
    orden = sorted((p for p in campo if p.position == pos), key=resto, reverse=True)
    mis_titulares |= {p.pid for p in orden[:DEDIC.get(pos, 0)]}
_flex = sorted((p for p in campo if p.position in FPOS and p.pid not in mis_titulares), key=resto, reverse=True)
mis_titulares |= {p.pid for p in _flex[:len(FLEX)]}
# protegidos = tus mejores TITULARES (un mariscal suplente nunca cuenta como "mejor")
protegidos = {p.pid for p in sorted((p for p in campo if p.pid in mis_titulares),
                                    key=resto, reverse=True)[:PROTEGER_MEJORES]}
print("Protegidos (nunca se ofrecen):", ", ".join(p.name for p in campo if p.pid in protegidos))
doy_pool = [p for p in campo if p.status not in NO_OFRECER and p.pid not in protegidos and resto(p) > 0]
limite = len(SLOTS) + (mi_ros.bench_size or 0)

filas, cercanos, sin_trade = [], [], []
for t, ros in rivales:
    suyos = [p for p in ros.players if p.position in BASICAS]
    base_ellos_real = alineacion(suyos, True)
    base_ellos_yahoo = alineacion(suyos, False)
    pido_pool = [p for p in suyos if p.status not in NO_PEDIR and p.position not in NO_CAMBIAR_POS and resto(p) > 0]
    en_foco = (not FOCO) or any(x.lower() in (t.manager or "").lower() for x in FOCO)
    motivos = Counter()
    encontrados, casi = [], []
    contador = itertools.count()
    for a, b in TAMANOS:
        for doy in itertools.combinations(doy_pool, a):
            if sum(p.pid in mis_titulares for p in doy) > MAX_TITULARES_DOY:
                continue
            ids_doy = {p.pid for p in doy}
            mios_sin = [p for p in mios if p.pid not in ids_doy]
            for pido in itertools.combinations(pido_pool, b):
                tu = (alineacion(mios_sin + list(pido), True) - base_mio).sum()
                if tu / NS < MIN_TU_SEMANA:
                    motivos["no te sube lo suficiente"] += 1
                    continue
                tu_yahoo = (alineacion(mios_sin + list(pido), False) - base_mio_yahoo).sum()
                if tu_yahoo < MIN_TU_YAHOO:
                    motivos["no te sube lo suficiente"] += 1
                    continue
                ids_pido = {p.pid for p in pido}
                suyos_d = [p for p in suyos if p.pid not in ids_pido] + list(doy)
                ellos_yahoo = (alineacion(suyos_d, False) - base_ellos_yahoo).sum()
                ellos_real = (alineacion(suyos_d, True) - base_ellos_real).sum()
                da, recibe = sum(resto(p) for p in pido), sum(resto(p) for p in doy)
                fila = {
                    "Equipo": etiqueta(t),
                    "Doy": nombres(doy),
                    "Recibo": nombres(pido),
                    "Tú pts/sem": round(tu / NS, 2),
                    "Tú ves en Yahoo (temporada)": round(tu_yahoo, 1),
                    "Él pts/sem (real)": round(ellos_real / NS, 2),
                    "Él ve en Yahoo (temporada)": round(ellos_yahoo, 1),
                    "Pts restantes: da / recibe": f"{da:.0f} / {recibe:.0f}",
                }
                fallas = []
                if ellos_yahoo < MIN_ELLOS_YAHOO:
                    fallas.append(("Yahoo se lo muestra como pérdida", f"Yahoo le muestra {ellos_yahoo:+.1f}"))
                if ellos_real < MIN_ELLOS_REAL:
                    fallas.append(("en la cuenta real él pierde", "en la cuenta real él pierde"))
                if recibe < MIN_JUSTO * da:
                    fallas.append(("no se ve justo (recibe menos puntos de los que da)",
                                   "recibe menos puntos de los que da"))
                if en_foco:
                    f2 = dict(fila, **{"Qué falla": ", ".join(c for _, c in fallas) or "nada: pasa"})
                    item = (ellos_yahoo + ellos_real, next(contador), f2)
                    if len(casi) < CERCANOS:
                        heapq.heappush(casi, item)
                    else:
                        heapq.heappushpop(casi, item)
                if fallas:
                    motivos[fallas[0][0]] += 1
                    continue
                activos_d = [p for p in mi_ros.players if p.slot != "IR" and p.pid not in ids_doy]
                fila["Nota"] = "tendrías que soltar a alguien" if len(activos_d) + len(pido) > limite else ""
                encontrados.append(fila)
    if encontrados:
        encontrados.sort(key=lambda r: (min(r["Tú pts/sem"], r["Él pts/sem (real)"]), r["Tú pts/sem"]),
                         reverse=True)
        filas += encontrados[:POR_EQUIPO]
    else:
        te_sirven = sum(motivos.values()) - motivos["no te sube lo suficiente"]
        if te_sirven == 0:
            razon = "ningún jugador suyo te sube la alineación lo suficiente"
        else:
            detalle = ", ".join(f"{n} porque {m}" for m, n in motivos.most_common()
                                if m != "no te sube lo suficiente")
            razon = f"{te_sirven} trades te servían a ti, pero se descartaron: {detalle}"
        sin_trade.append(f"{etiqueta(t)}: {razon}.")
    cercanos += [f for _, _, f in sorted(casi, reverse=True)]

print(f"\nSemanas {SEMANAS[0]} a {SEMANAS[-1]} ({NS} semanas). Tu alineación hoy: "
      f"{base_mio.sum() / NS:.1f} pts por semana en promedio.")
print("\nTABLA A · Trades que pasan todos los filtros")
if filas:
    display(pd.DataFrame(filas))
else:
    print("Ninguno con estos filtros.")
for linea in sin_trade:
    print(linea)
print(f"\nTABLA B · Los {CERCANOS} trades más cercanos con {', '.join(FOCO) or 'cada equipo'} "
      "(te sirven a ti; ordenados por lo que menos le duele a él)")
display(pd.DataFrame(cercanos)) if cercanos else print("Ninguno de sus jugadores te sube la alineación.")
print("\nTABLA C · Mapa de necesidades (titulares de cada posición vs el promedio de la liga)")
display(tabla_c)
print("\nAntes de mandar uno: ábrelo en el evaluador de Yahoo y confirma que a él le sale en verde.")

  leído Traffic Safety - Fourth Quarter Delio: 18 jugadores
  leído Traffic Safety - 0-17: 16 jugadores
  leído Traffic Safety - At least I'm not Dallas: 16 jugadores
  leído Traffic Safety - Better Luck NextYear: 15 jugadores
  leído Traffic Safety - End Zone Hunters: 16 jugadores
  leído Traffic Safety - Fahim n Furious: 16 jugadores
  leído Traffic Safety - Guap Goblin: 15 jugadores
  leído Traffic Safety - Mountain Drew: 18 jugadores
  leído Traffic Safety - Mountain Top: 16 jugadores
  leído Traffic Safety - Riddle Renegades: 16 jugadores
  leído Traffic Safety - Silly Old Sawyer: 16 jugadores
  leído Traffic Safety - T-Law & Fornication: 18 jugadores
Protegidos (nunca se ofrecen): Jaylen Warren, Bucky Irving, Puka Nacua, Nico Collins, Brock Purdy

Semanas 8 a 17 (10 semanas). Tu alineación hoy: 115.1 pts por semana en promedio.

TABLA A · Trades que pasan todos los filtros

,Equipo,Doy,Recibo,Tú pts/sem,Tú ves en Yahoo (temporada),Él pts/sem (real),Él ve en Yahoo (temporada),Pts restantes: da / recibe,Nota
0,End Zone Hunters (Douglas),Cam Skattebo + Brenton Strange,Emeka Egbuka,0.50,5.0,0.19,7.5,87 / 163,
1,End Zone Hunters (Douglas),Cam Skattebo + Brenton Strange,Emeka Egbuka + Hunter Henry,0.50,5.0,0.19,7.5,149 / 163,
2,End Zone Hunters (Douglas),Cam Skattebo + Brenton Strange,Jaylen Waddle,0.55,5.5,0.16,7.3,86 / 163,
3,Silly Old Sawyer (mike),Sam LaPorta + Malik Washington,Matthew Golden,0.66,6.6,0.70,12.8,102 / 185,
4,Silly Old Sawyer (mike),Sam LaPorta + Malik Washington,Matthew Golden + TreVeyon Henderson,0.66,6.6,0.70,12.8,160 / 185,
5,Silly Old Sawyer (mike),Sam LaPorta + Malik Washington,Matthew Golden + J.K. Dobbins,0.66,6.6,0.69,12.6,168 / 185,

0-17 (Gregg): 1728 trades te servían a ti, pero se descartaron: 1728 porque Yahoo se lo muestra como pérdida.
At least I'm not Dallas (JOSHUA): 3158 trades te servían a ti, pero se descartaron: 3158 porque Yahoo se lo muestra como pérdida.
Better Luck NextYear (Ron): 1757 trades te servían a ti, pero se descartaron: 1757 porque Yahoo se lo muestra como pérdida.
Fahim n Furious (Fahim): 2283 trades te servían a ti, pero se descartaron: 2283 porque Yahoo se lo muestra como pérdida.
Guap Goblin (Brian): 1961 trades te servían a ti, pero se descartaron: 1956 porque Yahoo se lo muestra como pérdida, 5 porque en la cuenta real él pierde.
Mountain Drew (Drew Commissioner): 2497 trades te servían a ti, pero se descartaron: 2491 porque Yahoo se lo muestra como pérdida, 5 porque en la cuenta real él pierde, 1 porque no se ve justo (recibe menos puntos de los que da).
Mountain Top (Tito): 1670 trades te servían a ti, pero se descartaron: 1670 porque Yahoo se lo muestra como pérdida.
Riddle Renegades (Keith): 2493 trades te servían a ti, pero se descartaron: 2493 porque Yahoo se lo muestra como pérdida.
T-Law & Fornication (Preston): 1747 trades te servían a ti, pero se descartaron: 1747 porque Yahoo se lo muestra como pérdida.

TABLA B · Los 3 trades más cercanos con cada equipo (te sirven a ti; ordenados por lo que menos le duele a él)

,Equipo,Doy,Recibo,Tú pts/sem,Tú ves en Yahoo (temporada),Él pts/sem (real),Él ve en Yahoo (temporada),Pts restantes: da / recibe,Qué falla
0,0-17 (Gregg),Sam LaPorta + Cam Skattebo,Saquon Barkley + Khalil Shakir,0.56,5.6,-0.34,-3.4,172 / 175,"Yahoo le muestra -3.4, en la cuenta real él pi..."
1,0-17 (Gregg),Sam LaPorta + Cam Skattebo,Saquon Barkley + Evan Engram,0.56,5.6,-0.34,-3.4,138 / 175,"Yahoo le muestra -3.4, en la cuenta real él pi..."
2,0-17 (Gregg),Sam LaPorta + Cam Skattebo,Courtland Sutton + Saquon Barkley,0.56,5.6,-0.34,-3.4,164 / 175,"Yahoo le muestra -3.4, en la cuenta real él pi..."
3,At least I'm not Dallas (JOSHUA),Sam LaPorta + Cam Skattebo,Jacoby Brissett + Ollie Gordon II,0.65,6.5,-0.20,-2.0,280 / 175,"Yahoo le muestra -2.0, en la cuenta real él pi..."
4,At least I'm not Dallas (JOSHUA),Xavier Worthy + Cam Skattebo,Ollie Gordon II + Caleb Douglas,1.70,17.0,-0.34,-3.4,177 / 156,"Yahoo le muestra -3.4, en la cuenta real él pi..."
5,At least I'm not Dallas (JOSHUA),Xavier Worthy + Cam Skattebo,Ollie Gordon II + Cade Otton,1.70,17.0,-0.34,-3.4,165 / 156,"Yahoo le muestra -3.4, en la cuenta real él pi..."
6,Better Luck NextYear (Ron),Sam LaPorta + Cam Skattebo,Harold Fannin Jr. + Breece Hall,0.50,5.0,-0.48,-5.5,171 / 175,"Yahoo le muestra -5.5, en la cuenta real él pi..."
7,Better Luck NextYear (Ron),Rachaad White + Brenton Strange,Breece Hall + Marvin Harrison Jr.,1.25,12.5,-1.01,-10.1,142 / 174,"Yahoo le muestra -10.1, en la cuenta real él p..."
8,Better Luck NextYear (Ron),Rachaad White + Brenton Strange,Jordan Addison + Breece Hall,1.26,12.6,-1.01,-10.1,180 / 174,"Yahoo le muestra -10.1, en la cuenta real él p..."
9,End Zone Hunters (Douglas),Geno Smith + Brenton Strange,Matthew Stafford + Emeka Egbuka,0.69,6.9,-0.08,20.4,279 / 241,"en la cuenta real él pierde, recibe menos punt..."
10,End Zone Hunters (Douglas),Geno Smith + Brenton Strange,Matthew Stafford + Jaylen Waddle,0.73,7.3,-0.10,20.2,278 / 241,"en la cuenta real él pierde, recibe menos punt..."
11,End Zone Hunters (Douglas),Geno Smith + Josh Downs,Matthew Stafford + Emeka Egbuka,0.70,7.0,-0.29,12.6,279 / 230,"en la cuenta real él pierde, recibe menos punt..."
12,Fahim n Furious (Fahim),Denzel Boston + Josh Downs,Jameson Williams + Adonai Mitchell,0.58,5.8,-0.44,-4.4,142 / 157,"Yahoo le muestra -4.4, en la cuenta real él pi..."
13,Fahim n Furious (Fahim),Denzel Boston + Josh Downs,Jameson Williams + Kyle Monangai,0.58,5.8,-0.44,-4.4,162 / 157,"Yahoo le muestra -4.4, en la cuenta real él pi..."
14,Fahim n Furious (Fahim),Denzel Boston + Josh Downs,Jameson Williams + Brian Thomas Jr.,0.58,5.8,-0.44,-4.4,134 / 157,"Yahoo le muestra -4.4, en la cuenta real él pi..."
15,Guap Goblin (Brian),Sam LaPorta + Rachaad White,Luther Burden III + Cooper Kupp,0.72,7.2,0.37,4.7,161 / 186,Yahoo le muestra +4.7
16,Guap Goblin (Brian),Sam LaPorta + Rachaad White,Luther Burden III + Jerry Jeudy,0.72,7.2,0.37,4.7,136 / 186,Yahoo le muestra +4.7
17,Guap Goblin (Brian),Sam LaPorta + Rachaad White,Luther Burden III + Brian Robinson Jr.,0.72,7.2,0.37,4.7,150 / 186,Yahoo le muestra +4.7
18,Mountain Drew (Drew Commissioner),Sam LaPorta + Cam Skattebo,Colston Loveland + Caleb Williams,0.66,6.6,0.05,6.2,292 / 175,recibe menos puntos de los que da
19,Mountain Drew (Drew Commissioner),Sam LaPorta + Josh Downs,Colston Loveland + Caleb Williams,0.60,6.0,-0.03,5.4,292 / 177,"en la cuenta real él pierde, recibe menos punt..."
20,Mountain Drew (Drew Commissioner),Denzel Boston + Sam LaPorta,Colston Loveland + Caleb Williams,0.51,5.1,-0.05,5.2,292 / 180,"en la cuenta real él pierde, recibe menos punt..."
21,Mountain Top (Tito),Cam Skattebo + Josh Downs,DeVonta Smith + Devaughn Vele,0.71,7.1,-0.45,1.2,142 / 152,"Yahoo le muestra +1.2, en la cuenta real él pi..."
22,Mountain Top (Tito),Cam Skattebo + Josh Downs,DeVonta Smith + Deshaun Watson,0.71,7.1,-0.45,1.2,217 / 152,"Yahoo le muestra +1.2, en la cuenta real él pi..."
23,Mountain Top (Tito),Cam Skattebo + Josh Downs,DeVonta Smith + Kalif Raymond,0.71,7.1,-0.45,1.2,144 / 152,"Yahoo le muestra +1.2, en la cuenta real él pi..."
24,Riddle Renegades (Keith),Sam LaPorta + Rachaad White,A.J. Brown + Patrick Mahomes,0.52,5.2,-0.20,-1.2,311 / 186,"Yahoo le muestra -1.2, en la cuenta real él pi..."
25,Riddle Renegades (Keith),Sam LaPorta + Cam Skattebo,A.J. Brown + Tyler Allgeier,0.73,7.3,-0.64,-5.6,155 / 175,"Yahoo le muestra -5.6, en la cuenta real él pi..."
26,Riddle Renegades (Keith),Sam LaPorta + Cam Skattebo,A.J. Brown + Keon Coleman,0.73,7.3,-0.64,-5.6,166 / 175,"Yahoo le muestra -5.6, en la cuenta real él pi..."
27,Silly Old Sawyer (mike),Sam LaPorta + Xavier Worthy,Matthew Golden + Ray Davis,0.62,6.2,0.75,13.3,113 / 182,nada: pasa
28,Silly Old Sawyer (mike),Sam LaPorta + Xavier Worthy,Matthew Golden + Chig Okonkwo,0.62,6.2,0.75,13.3,168 / 182,nada: pasa
29,Silly Old Sawyer (mike),Sam LaPorta + Xavier Worthy,Matthew Golden + J.K. Dobbins,0.62,6.2,0.75,13.3,168 / 182,nada: pasa
30,T-Law & Fornication (Preston),Sam LaPorta + Rachaad White,George Kittle + Jakobi Meyers,0.59,5.9,-0.13,3.1,187 / 186,"Yahoo le muestra +3.1, en la cuenta real él pi..."
31,T-Law & Fornication (Preston),Sam LaPorta + Cam Skattebo,George Kittle + Antonio Williams,1.07,10.7,-0.40,0.4,162 / 175,"Yahoo le muestra +0.4, en la cuenta real él pi..."
32,T-Law & Fornication (Preston),Sam LaPorta + Cam Skattebo,Omar Cooper Jr. + George Kittle,1.07,10.7,-0.40,0.4,162 / 175,"Yahoo le muestra +0.4, en la cuenta real él pi..."

TABLA C · Mapa de necesidades (titulares de cada posición vs el promedio de la liga)

,Equipo,Más débil en,Más fuerte en,Le sobra en la banca
0,TÚ,RB (+0.2 pts/sem vs liga),WR (+2.2),"Geno Smith (QB 15.2), Rachaad White (RB 8.6)"
1,0-17 (Gregg),WR (-2.0 pts/sem vs liga),QB (+4.2),"C.J. Stroud (QB 18.3), Chris Godwin Jr. (WR 7.3)"
2,At least I'm not Dallas (JOSHUA),QB (+0.7 pts/sem vs liga),TE (+2.9),"Jacoby Brissett (QB 17.0), Ollie Gordon II (RB..."
3,Better Luck NextYear (Ron),RB (-3.6 pts/sem vs liga),WR (+2.0),"Tyler Shough (QB 18.4), Jordan Addison (WR 8.1)"
4,End Zone Hunters (Douglas),TE (-1.6 pts/sem vs liga),WR (+1.8),"Matthew Stafford (QB 19.2), Jaylen Waddle (WR ..."
5,Fahim n Furious (Fahim),WR (-1.4 pts/sem vs liga),TE (+2.1),"Malik Willis (QB 17.5), Kyle Monangai (RB 6.6)"
6,Guap Goblin (Brian),QB (-5.9 pts/sem vs liga),RB (+2.3),"DK Metcalf (WR 8.5), Mark Andrews (TE 6.6)"
7,Mountain Drew (Drew Commissioner),RB (-3.4 pts/sem vs liga),QB (+2.2),"Caleb Williams (QB 20.7), Ladd McConkey (WR 9.1)"
8,Mountain Top (Tito),WR (-3.0 pts/sem vs liga),QB (+0.5),"Jordan Love (QB 18.7), Deshaun Watson (QB 12.9)"
9,Riddle Renegades (Keith),RB (-0.9 pts/sem vs liga),TE (+2.3),"Patrick Mahomes (QB 20.8), Tre Tucker (WR 7.5)"
10,Silly Old Sawyer (mike),QB (-2.0 pts/sem vs liga),RB (+4.9),"Aaron Rodgers (QB 16.7), Matthew Golden (WR 10.2)"
11,T-Law & Fornication (Preston),RB (-1.8 pts/sem vs liga),TE (+1.1),"Bo Nix (QB 17.4), Pat Freiermuth (TE 6.5)"

Antes de mandar uno: ábrelo en el evaluador de Yahoo y confirma que a él le sale en verde.

In [ ]:
#@title 7. Evaluar un trade { display-mode: "form" }
DOY = ""  #@param {type:"string"}
RECIBO = ""  #@param {type:"string"}
#@markdown Nombres separados por coma, por ejemplo DOY = `Nico Collins`, RECIBO = `Josh Allen`.
#@markdown Solo para jugadores **con dueño**. Un agente libre (como los de la celda 6) se agrega en waivers, no por trade.
r = pilot.run("trade", give=[x.strip() for x in DOY.split(",") if x.strip()],
              get=[x.strip() for x in RECIBO.split(",") if x.strip()])
print(r.title, "\n")
print(r.text)

In [20]:
#@title 8. Piloto automático del domingo (deja esta pestaña abierta) { display-mode: "form" }
HORAS = 10  #@param {type:"number"}
CADA_MINUTOS = 10  #@param {type:"integer"}
#@markdown Empiézala 90 minutos antes del PRIMER partido de tus titulares (si alguno juega a las 9:30 am en Europa, a las 8:00 am; si no, antes de las 11:30 am). La celda 4 te dice la hora exacta en "PRÓXIMO CONTROL". Solo revisa de verdad cuando falta poco para un partido;
#@markdown si un titular sale inactivo, lo cambia (modo `automatico`) o te manda una alerta urgente (modo `sugerir`).
#@markdown **Nuevo (20 oct):** además de inactivos revisa la **alerta de rol** (titular activo que perdió el puesto),
#@markdown repite cada 30 minutos una alerta urgente que nadie atendió (hasta 4 veces) y, si un titular queda fuera
#@markdown sin suplente en tu banca, te dice qué agente libre agregar.
pilot.loop(hours=HORAS, every_minutes=CADA_MINUTOS)

[07:55] Sin partidos próximos
[08:05] Sin partidos próximos
[08:15] Sin partidos próximos
[08:25] Sin partidos próximos
[08:35] Sin partidos próximos

KeyboardInterrupt:

## 9. Calibrar la escritura en Yahoo (una vez, antes de `automatico`)

Esta celda **no guarda ni puja nada**: abre Yahoo en un navegador invisible con tu sesión, hace los clics hasta el último paso y toma **capturas**.
Mira las imágenes: en la de la alineación deben verse los menús con las posiciones nuevas; en la de la puja, marcado el jugador a soltar y escrita la cantidad.
Si algo no coincide, no uses `automatico` para eso y avísame con la captura.

In [ ]:
#@title 9. Calibrar (simulacro con capturas) { display-mode: "form" }
PROBAR_ALINEACION = True  #@param {type:"boolean"}
PROBAR_PUJA = False  #@param {type:"boolean"}
JUGADOR_A_PEDIR = ""  #@param {type:"string"}
SOLTAR = ""  #@param {type:"string"}
PUJA = 1  #@param {type:"integer"}
from IPython.display import Image

nav = pilot.browser()
if nav is None:
    raise SystemExit("Instala el navegador: vuelve a correr la celda 1 con INSTALAR_NAVEGADOR marcado.")

def mostrar(res):
    print(("✅ " if res.ok else "❌ ") + res.detail)
    for ruta in res.evidence:
        if ruta.endswith(".png"):
            display(Image(filename=ruta, width=900))

if PROBAR_ALINEACION:
    from fantasy_autopilot.optimizer import optimize_lineup, plan_moves
    plan = optimize_lineup(roster.players, roster.slots, pilot.opt_settings())
    objetivo = {m.player.pid: m.to_slot for m in plan_moves(roster.players, plan)}
    if not objetivo:  # lineup already optimal: rehearse swapping a bench player with a starter
        for b in (p for p in roster.players if p.slot == "BN" and not p.locked):
            s = next((p for p in roster.players if p.is_starter and not p.locked and b.can_fill(p.slot)), None)
            if s:
                objetivo = {s.pid: "BN", b.pid: s.slot}
                break
    print("Cambios que se ensayan (no se guardan):", objetivo)
    mostrar(nav.set_lineup(objetivo, semana, dry_run=True))

if PROBAR_PUJA:
    info = pilot.sleeper.match(name=JUGADOR_A_PEDIR) if pilot.sleeper else None
    pid = str((info or {}).get("yahoo_id") or "")
    soltar = roster.find(SOLTAR) if SOLTAR else None
    if not pid:
        print("No encontré el id de Yahoo de", JUGADOR_A_PEDIR)
    else:
        mostrar(nav.claim(pid, soltar.pid if soltar else None, PUJA, dry_run=True))

## 10. 24/7 sin Colab (GitHub Actions, gratis)

Colab se apaga cuando cierras la pestaña. El mismo programa puede correr en los servidores de GitHub con horario fijo (tu repo ya trae el archivo `.github/workflows/autopilot.yml`):

| Cuándo (hora del Este) | Qué hace |
|---|---|
| Todos los días ~10:07 am | Alineación de la semana |
| Martes ~6:37 pm | Waivers y pujas FAAB |
| Jueves, sábado, domingo y lunes, cada 15 min cerca de los partidos | Inactivos del día de partido |

Pasos (en github.com/delioguzmang-maker/fanatasy → **Settings → Secrets and variables → Actions**):
1. Pestaña **Secrets** → *New repository secret*: `YAHOO_COOKIES` (el mismo valor de la celda 3) y `NTFY_TOPIC` (tu tema).
2. Pestaña **Variables** → *New repository variable*: `FA_LEAGUE_ID`, `FA_TEAM_ID`, `FA_MODE` (`sugerir` o `automatico`) y `AUTOPILOT_ENABLED` = `true`.
3. Opcional: `FA_AUTO_CLAIMS` = `true` para que también puje (solo después de calibrar).
4. Para otras opciones (nunca soltar, probabilidades manuales) crea el secreto `FA_CONFIG_JSON`, por ejemplo:
   `{"never_drop": ["Alec Pierce"], "p_play_overrides": {"Puka Nacua": 0.3}}`

Tu repositorio es **público**: los registros de GitHub solo muestran el título de cada corrida, nunca tus cookies. GitHub solo corre horarios desde la rama principal del repo.

## Problemas frecuentes

* **"Sesión de Yahoo vencida"**: repite la celda 3 (copia de nuevo la cookie) y actualiza el secreto `YAHOO_COOKIES` (también en GitHub si lo usas).
* **"No se leyó ningún jugador"**: Yahoo cambió la página. Corre la celda 9 y comparte la captura.
* **El guardado falla en `automatico`**: el programa te manda el aviso con los cambios exactos para hacerlos a mano en la app de Yahoo (30 segundos).
* **Las pujas**: el monto es una regla, no un dato. `PUJA_MAXIMA_PCT` limita cuánto de tu saldo se puede ir en un jugador.